### ISSUE TITLE
Backup/Restore (repos, app installed, settings, etc.)

### ISSUE THREAD

**Issue by serrq** [Droid-ify/client#145]
The repositories are starting to be many, the installed apps don't need to be saved in their entirety, just the list of headers so that if I need to move to a new device I upload the droid-ify.zip file and just have to download all the apps that are already there but just need to be pulled down from the network.
Same thing for the settings.

A selective backup would be needed for the list of apps so that customized backups could be created to share to other people.

**Comment by vertigo220** [comment]
Semi-duplicate of issue #19, only difference being this involves backing up list of installed apps as well.

**Comment by its-thomas** [comment]
May I ask when we might be able to have the above features in an update of your awesome Droid-ify app? 😍

**Comment by laraib07** [comment]
Also backup list of favourite apps

**Comment by Iamlooker** [comment]
> May I ask when we might be able to have the above features in an update of your awesome Droid-ify app? 😍

I cannot guarantee the time but this will come after the new index format is implemented

**Comment by zerobun** [comment]
Just came here to create a issue about this, hope it gets implemented soon🙏❤️

**Comment by Iamlooker** [comment]
Only installed app feature is not implemented yet. And is not planned in near future. As many micro issues with installer needs to be fixed and a larger `InstallManager` implementation is needed
