### ISSUE TITLE
Backup/Restore Configuration

### ISSUE THREAD

**Issue by balporig** [Droid-ify/client#19]
The ability to backup configuration including Repositories to a file (for eg. `.json` file) and restore it on another device

**Comment by Iamlooker** [comment]
Ya this would be a good idea let me see how I can implement this

**Comment by Bugaddr** [comment]
> The ability to backup configuration including Repositories to a file (for eg. `.json` file) and restore it on another device

This sounds good, we can use the sql database saved in data directory. Json would not be a better alternative for app db, rather json can be considered for app preferences. But i feel backing up preferences is unnecessary since there are very few preferences currently.

**Comment by Turhvjbufv** [comment]
Any update?
