### ISSUE TITLE
Speed up auto-scroll to top

### ISSUE THREAD

**Issue by vertigo220** [Droid-ify/client#195]
With the new green up arrow button that scrolls back to the beginning of the app list, it should jump back up rather than scrolling, or at least scroll faster. I scrolled down manually for five seconds and it took a full three seconds for it to scroll back up when I tapped the button. Not really a big deal, but there's no reason to have it take even this long.

**Comment by GameOverFlowChart** [comment]
I think it makes sense to make the speed relative to the distance so that scrolling up always takes the same amount of time. Or make it an acceleration relative to the distance, so that it starts smooth but in total always takes the same time to reach the top.

**Comment by vertigo220** [comment]
But the only way to make it always take the same amount of time is to make it instant. Otherwise, how could it take the same amount of time whether you've scrolled one screen or 30? Either that, or auto-scrolling back up after scrolling down just a page or two would have to be very slow.

**Comment by GameOverFlowChart** [comment]
> But the only way to make it always take the same amount of time is to make it instant.

Wrong.

>Otherwise, how could it take the same amount of time whether you've scrolled one screen or 30?

We call that magic "Math".

**Comment by mecuricat** [comment]
There is an instant messenger called [monocles chat](https://codeberg.org/Arne/monocles_chat) which has an instant scroll to bottom feature. Perhaps their (GPL-3.0 licensed) code can be used to replace their **bottom** scroll to **top** scroll for Droid-ify.
