### ISSUE TITLE
Toggle for disabling animation effect when you open an app page

### ISSUE THREAD

**Issue by mecuricat** [Droid-ify/client#247]
**Is your feature request related to a problem? Please describe.**
I am not against animation or transition effects. But when you open an app page, there is a blinking animation effect. Unless it is necessary to conceal the loading time, I would prefer to disable it.

https://user-images.githubusercontent.com/89805719/218164088-ac13c5f1-ff11-4d64-a43e-57a9d448089c.mp4

**Describe the solution you'd like**
A toggle in settings to disable transition effects.

**Comment by Iamlooker** [comment]
Sorry for late reply, I was not very active for past few days. I am feeling really down, nothing related.

Anyways, I will look into this. I am planning to move TopAppBar to activity so that when a new page is opened it will not manually collapse but stays collapsed 😃

**Comment by mecuricat** [comment]
No, I just realized I don't mind it as much as I thought I did. I was being too picky. I should have mentioned why I closed the issue.

> I am planning to move TopAppBar to activity so that when a new page is opened it will not manually collapse but stays collapsed

Mind reader. I was about to create a specific issue about the top bar. It behaves weirdly and collapses itself during the transition from home page to Settings page. I think what you planned will solve this too.

https://user-images.githubusercontent.com/112750975/220836992-c3bf79b5-4ef0-4c8a-88aa-a2bf155d125f.mp4

##### Describe what you would like me to do

###### Feel better and feel good. :) Droid-ify isn't going anywhere and we are here to stay.
###### If you like to read, I would recommend [My India](https://archive.org/details/dli.ernet.527278) by Jim Corbett. If you like to binge watch, I would recommend [Reset](https://www.youtube.com/playlist?list=PLuidrAcAGAOPi5WYn76kRIro_C0R9sok_).

**Comment by mecuricat** [comment]
This issue has been resolved. The transition effect is extremely smooth. Closing this.
