### ISSUE TITLE
[BUG] apps are not upgraded when "auto update apps" option is enabled

### ISSUE THREAD

**Issue by soredake** [Droid-ify/client#317]
**Describe the bug**
I have set "Sync repositories automatically" to "only on wifi", installer set to "Shizuku", both shizuku and droid-ify are excluded from battery optimiztation, i've enabled  "auto update apps", but still after a week my apps are not updated, thought repos are still updated.

**To Reproduce**
1. Install shizuku and droid-ify
2. Enabled auto-updates and set installer to shizuku
3. Wait for a week
4. Repos are updated, but not apps

**Expected behavior**
Apps should been upgraded.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab A 10.1 (2019)
 - OS: Android 11
 - Version 0.5.7

**Additional context**

**Comment by Iamlooker** [comment]
Were you getting notifications?

**Comment by soredake** [comment]
@Iamlooker no, i have them disabled.

**Comment by Iamlooker** [comment]
> @Iamlooker no, i have them disabled.

I will look into it

**Comment by soredake** [comment]
Apps are still not upgraded automatically in background on [0.6.1](https://github.com/Droid-ify/client/releases/tag/v0.6.1)

**Comment by soredake** [comment]
I've updated droid-ify to 0.6.2 on two devices, tablet with shizuku and not updated repos, and phone with session installer and updated repos, after waiting for a day auto upgrade is finally happened in background on tablet, but not on phone. Is droid-ify upgrading apps only when update is found first time after updating repos?

**Comment by Iamlooker** [comment]
> I've updated droid-ify to 0.6.2 on two devices, tablet with shizuku and not updated repos, and phone with session installer and updated repos, after waiting for a day auto upgrade is finally happened in background on tablet, but not on phone. Is droid-ify upgrading apps only when update is found first time after updating repos?

Yes, that is the intende behaviour for now. But I will try and improve it in future

**Comment by soredake** [comment]
Closing as this is fixed now.
