### ISSUE TITLE
[HELP NEEDED] Need designers for Website

### ISSUE THREAD

**Issue by iamthecloverly** [Droid-ify/client#319]
We at Droidify, a leading provider of Android products and services, are in need of experienced designers to help us revamp our website. Our goal is to create a modern, visually appealing website that showcases our products and services in the best possible way.

We are looking for designers who can work with us to create a user-friendly interface that is easy to navigate, with a clean and minimalist design. The website should be optimized for mobile devices and should provide an excellent user experience to our customers.

If you have experience designing websites and are interested in working with us, please leave a comment on this issue or send us a message. We are open to working with both experienced designers and those who are just starting out.

Your contribution will play a vital role in enhancing the online presence of Droidify and improving the experience of our customers. We look forward to hearing from you soon.

Thank you for your time and interest!

Best regards,
The Droidify Team.

**Comment by meenbeese** [comment]
I am interested in contributing to make your website better! I could only help with the HTML and CSS though, as I don't have any JS knowledge. What do you have in plan for the website?

**Comment by iamthecloverly** [comment]
> I am interested in contributing to make your website better! I could only help with the HTML and CSS though, as I don't have any JS knowledge. What do you have in plan for the website?

Hey @meenbeese,
Thank you for interest to help me out.
We are searching for Figma designers to design content for our website.
If you are interested in that, please reach me out.

**Comment by meenbeese** [comment]
Hey @iamthecloverly, I am really sorry for the late reply but I am interested in designing content for your website with Figma. Should we discuss the prototype contents in this thread or should I like email you? I wouldn't want to spam the issues page with messages just to get some feedback on what I've done. Otherwise, it would be a joy for me to try to help with the website.

**Comment by Iamlooker** [comment]
😉
