### ISSUE TITLE
Add Funkwhale's F-Droid repository

### ISSUE THREAD

**Issue by taivlam** [Droid-ify/client#321]
**Is your feature request related to a problem? Please describe.**
I would like the custom Funkwhale [repository](https://fdroid.funkwhale.audio/) to be on the list of Droid-ify's optional repositories.

**Describe the solution you'd like**
I would like the Funkwhale [repository](https://fdroid.funkwhale.audio/) to be added on the list of Droid-ify's optional repositories.

**Describe alternatives you've considered**
I could manually add Funkwhale's repository app info into Droid-ify, but I can't seem to do this by scanning the QR code in [Binary Eye](https://github.com/markusfisch/BinaryEye) and using the "Share with..." menu with the output of the QR code.

**Additional context**
From a recent Funkwhale blog [post](https://blog.funkwhale.audio/ffa-020-release.html), Funkwhale's repo is described to offer current versions of its app sooner than the official F-Droid [version](https://f-droid.org/en/packages/audio.funkwhale.ffa/).

From my understanding, this situation is similar to that of [Newpipe](https://newpipe.net/): there is a version officially published by F-Droid, but it also maintains its own F-Droid [repo](https://archive.newpipe.net/fdroid/repo/?fingerprint=E2402C78F9B97C6C89E97DB914A2751FDA1D02FE2039CC0897A462BDB57E7501) so that versions closer to upstream can be given to users.

**Comment by HarriBuh** [comment]
You can easily add them to your current repos, why would you want it to become officially added? I don't see any advantages here.

**Comment by Iamlooker** [comment]
Merge with #349
