### ISSUE TITLE
[BUG] Cannot get out of screenshot list

### ISSUE THREAD

**Issue by opk12** [Droid-ify/client#322]
**Describe the bug**
I am stuck in the enlarged screenshot list. I cannot return back to the Droid-ify GUI.

**To Reproduce**
1. I click on the screenshot of an app.
2. I can navigate to the next / previous screenshots, but I cannot return back to the Droid-ify. At the bottom of the screen, there is the spacing for the apps list / Show desktop / Back button. However clicking there does nothing.
3. Locking / unlocking the screen by pressing the Power button does not help.
4. I escaped thanks to a notification (Droid-ify lack of permissions to install).

**Expected behavior**
The Back button should work.

**Screenshots**
The appearance is normal as seen on other phones (screenshot centered on the screen and empty bar below it), it's just that clicking where the Back button usually is won't work.

**Smartphone (please complete the following information):**
This is a Samsung phone with Android 11 and One UI 3.1.

This does *not* happen on another Samsung phone with Android 10 and One UI 2.5 with the same Droid-ify settings.

**Comment by Iamlooker** [comment]
I think you can swipe up to show the Navigation Bar, can you try this.

**Comment by opk12** [comment]
Thank you, the navigation bar appears by swiping up on the bottom border of the screen or swiping down on the upper border of the screen. Swiping elsewhere has no effect. What about a visual hint (message or arrow)?

**Comment by Iamlooker** [comment]
> Thank you, the navigation bar appears by swiping up on the bottom border of the screen or swiping down on the upper border of the screen. Swiping elsewhere has no effect. What about a visual hint (message or arrow)?

What about a back icon? I will try this after I am done with #309

**Comment by opk12** [comment]
If it's simple and intuitive (self-explanatory) I think it's fine.

**Comment by woj-tek** [comment]
I'm struggling with something similar - quite often I open the screenshot and the will try to tap on the back icon... which is just part of the screenshot and not the actual system back icon so I will have to swipe up and then back.

Would it be possible to either not do fullscreen screenshot or not hide navigation bar by default?

(I'm not sure why Google / Android is pushing swipe UI so hard... it's imprecise and inconvenient most of the time...)

**Comment by Iamlooker** [comment]
Can you test alpha build in the Telegram Group: https://t.me/droidifyc

**Comment by opk12** [comment]
Thank you! Same - the phone's owner would be happy to test a non-`CurrentVersion` update from F-droid, (and I'm on Matrix actually)

**Comment by BabyOilJohnson** [comment]
@Iamlooker can u make the screenshot normal view other than full screen view so that it makes easy to get out of it by a single back click.

**Comment by Iamlooker** [comment]
@BabyOilJohnson hav you tried the latest release?

**Comment by BabyOilJohnson** [comment]
Yeah, I'm using the latest one.
v0.5.9

**Comment by Iamlooker** [comment]
> Yeah, I'm using the latest one.
> v0.5.9

There is supposed to be a back button right?

**Comment by BabyOilJohnson** [comment]
Yeah, there is a back button in the screenshot page but I have to double click the button to get out of it.

**Comment by woj-tek** [comment]
@Iamlooker I was somewhat confused as I didn't saw the button at first - you are right there is a back button but... it's in the upper-left corner so it's quite difficult to reach with one hand.

Would it be possible to just do something more native - open the screenshot fullscreen, but with navigation bar visible (and possibly hide it when tapping on the screen)? Most of the apps that display image / video (fullscreen do it that way). Biggest benefit is easy way to get out of the screenshot view and easy way to see it without system decoration... and it also feels like a more common scenario :-)
