### ISSUE TITLE
[BUG] Behavior of "Update All" button

### ISSUE THREAD

**Issue by du33169** [Droid-ify/client#325]
**Describe the bug**
The "Update All" Button doesn't show up after manual refresh on the "Updates" Tab, 
also not disappear after every update is installed.

**To Reproduce**
1. Go to the 'Updates' Tab
2. Click on the 'Refresh' Button
3. Apps with updates appear in the list, but the "update all" button **doesn't show up**
4. Only after entering the detail page of any app and swiping back will the 'update all' button show up
5. click the "Update All" button and wait for the installation to complete
6. Message shows up "All your applications are up to date, but the "update all" button **is still there**

**Expected behavior**
The "Update All" button shows up if there are any updates, and disappear when everything is up to date.

**Screenshots**
(sorry I have to wait for the next time when any app has update to get a screenshot)

**Smartphone (please complete the following information):**
 - Device: Huawei Nova 4i
 - OS: Android 10
 - Version: v0.5.7

**Additional context**
-

**Comment by Iamlooker** [comment]
Ooh I also noticed this. I will focus on this after #309 is fixed
