### ISSUE TITLE
[BUG] Application crashes on launch if root installer is selected and root permissions are lost

### ISSUE THREAD

**Issue by DerivativeOfLog7** [Droid-ify/client#326]
**Describe the bug**
Doidify crashes on launch if the root installer method is selected and the root permissions are lost afterwards

**To Reproduce**
1. Set installer type to root installer
2. Fully close (force stop) Droidify
3. Revoke root permissions for Droidify
4. Try to launch Droidify again

**Expected behavior**
Droidify shouldn't crash on launch

**Smartphone (please complete the following information):**
 - Device:  Xiaomi Mi 10 (umi)
 - OS: Android 13
 - Version 0.5.7

**Additional context**
Tested with Magisk, also happens if Magisk is uninstalled (found out when I forgot to reflash Magisk after an update)

**Comment by Iamlooker** [comment]
This should have been fixed in `Release 0.5.8 Patch 4` and subsequent releases. Can you please check.

**Comment by DerivativeOfLog7** [comment]
Yes - works on two devices with different arch and even after uninstalling Magisk
