### ISSUE TITLE
[BUG] Version buttons not active after action

### ISSUE THREAD

**Issue by haarp** [Droid-ify/client#327]
**Describe the bug**
After an action was performed (e.g. deleting an installed app), the version buttons (to install a specific version) do not work. You can press them, but nothing will happen. If you go back and enter the appplication overview again, the version buttons will work again.

**To Reproduce**
1. Go to app overview for app X
2. Click on Delete
3. Scroll down to versions and try to manually install one by tapping it
4. -> Nothing happens
5. Go back and return to app overview for app X
6. Scroll down to versions again and try to manually install one by tapping it
7. -> Now it works

**Expected behavior**
Version buttons should always work

**Screenshots**
--

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - OS: Android 10
 - Version: 0.5.7

Thanks!

**Comment by Iamlooker** [comment]
This is probably fixed in the upcoming update, you can test it in the debug build in the `Actions` tab in GitHub website

**Comment by Iamlooker** [comment]
Is this still happening?

**Comment by Iamlooker** [comment]
-STALE-
