### ISSUE TITLE
Add support for `fdroidrepo://` URLs

### ISSUE THREAD

**Issue by balporig** [Droid-ify/client#33]
`fdroidrepo://` is supported by the official client to add a new HTTP repository (and `fdroidrepos://` for HTTPS). This is handy because it allows a website to expose a button with a link which directly opens up the F-Droid store page to add a new repository with all the info pre-filled.

**Comment by Iamlooker** [comment]
Can you please share a sample of this, It would be helpful

**Comment by Iamlooker** [comment]
I can't even make them work on Official client

and idk how to implement this perfectly as there is no documentation

**Comment by revuwa** [comment]
AFAIK the fdroidrepos:// just have to be replaced with https:// as Neo Store does it here:
https://github.com/NeoApplications/Neo-Store/commit/db08d75e7bb20591971745dc045a8d54423b1cd9

So a valid example should be like this:

- fdroidrepos://releases.threema.ch/fdroid/repo?fingerprint=5734E753899B25775D90FE85362A49866E05AC4F83C05BEF5A92880D2910639E

which's listed here: https://threema.ch/en/faq/libre_installation
