### ISSUE TITLE
[BUG] Repos refresh not working

### ISSUE THREAD

**Issue by ruben-tura** [Droid-ify/client#331]
**Describe the bug**
The repositories don't refresh.

**To Reproduce**
1. Open app
2. Click on refresh icon
3. Nothing happens

**Expected behavior**
The refresh should start

**Smartphone (please complete the following information):**
 - Device: Xiaomi mi 11 lite 5g
 - OS: Android 13, MIUI 14
 - Version: Droid-ify v0.5.7

**Comment by Iamlooker** [comment]
This is maybe because there is nothing to update.
