### ISSUE TITLE
[BUG] Favorites causes crash after configuring repositories

### ISSUE THREAD

**Issue by raniesantos** [Droid-ify/client#333]
**Describe the bug**
App doesn't know how to handle showing favorites when some repos are disabled, and it immediately crashes.

**To Reproduce**
1. Add favorites from multiple different repos
2. Disable one of the repos
3. Try to open Favorites, app crashes

**Expected behavior**
It should probably just avoid trying to load favorites from disabled repos.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Nokia G10
 - OS: Android 12
 - Version: v0.5.7

**Comment by Iamlooker** [comment]
I will look into this, thanks

**Comment by Fehertukor** [comment]
I have the same problem.
Tried to find a solution with enabling all repositorys.
But after refresh and reload it did crash again and again.

Please check this problem if you have time!
And thank you for your work!

If it is too complex for now, an option to extract favorites from settings to en external file would help.
(I favorited a ton sadly did not save them any other way.)

**Comment by Iamlooker** [comment]
Fixed and will be available in 19-Aug update
