### ISSUE TITLE
Shizuku is not running warning

### ISSUE THREAD

**Issue by GGORG0** [Droid-ify/client#342]
**Is your feature request related to a problem? Please describe.**
If I sometimes forget to start Shizuku and then wonder why my apps just don't install/update.

**Describe the solution you'd like**
Some kind of error message that Shizuku is not running, but you have it selected as the installer type, which gives you 3 options: launch Shizuku app, change installer type or exit. Make sure to check for it right before installation and when opening Droid-ify.

**Describe alternatives you've considered**
Maybe just quietly reset/fallback to the session installer if Shizuku is not running, similarly to the root installer option.

**Comment by Iamlooker** [comment]
This has been implemented since v0.5.8 Patch X
