### ISSUE TITLE
Add some more preconfigured Repos

### ISSUE THREAD

**Issue by trytomakeyouprivate** [Droid-ify/client#349]
If I find the time I can try to implement this:

Twinhelix (Signal FOSS)
https://fdroid.twinhelix.com/fdroid/repo?fingerprint=7b03b0232209b21b10a30a63897d3c6bca4f58fe29bc3477e8e3d8cf8e304028

iodéOS
https://raw.githubusercontent.com/iodeOS/fdroid/master/fdroid/repo?fingerprint=ec43610d9acca5d2426eb2d5eb74331930014de79d3c3acbc17dfe58aa12605f

PeterCxy's F-Droid Repo
https://fdroid.typeblog.net?fingerprint=1a7e446c491c80bc2f83844a26387887990f97f2f379ae7b109679feae3dbc8c

SpiritCroc (Schildichat)
https://s2.spiritcroc.de/fdroid/repo?fingerprint=6612ade7e93174a589cf5ba26ed3ab28231a789640546c8f30375ef045bc9242

Cryptomator
https://static.cryptomator.org/android/fdroid/repo?fingerprint=f7c3ec3b0d588d3cb52983e9eb1a7421c93d4339a286398e71d7b651e8d8ecdd

DivestOS unofficial
https://divestos.org/apks/unofficial/fdroid/repo?fingerprint=a18cdb92f40ebfbbf778a54fd12dbd74d90f1490cb9ef2cc6c7e682dd556855d

FFUpdater
https://raw.githubusercontent.com/Tobi823/ffupdaterrepo/master/fdroid/repo?fingerprint=6e4e6a597d289cb2d4d4f0e4b792e14cce070bda6c47af4918b342fa51f2dc89

I2P
https://f-droid.i2p.io/repo?fingerprint=22658cc69f48d63f63c3d64e2041c81714e2749f3f6e5445c825297a00ddc5b6

KDE's Android repository
https://cdn.kde.org/android/stable-releases/fdroid/repo/?fingerprint=13784ba6c80ff4e2181e55c56f961eed5844cea16870d3b38d58780b85e1158f

Partido Interdimensional Pirata
https://fdroid.partidopirata.com.ar/fdroid/repo?fingerprint=3df6969ea3a2186d8a5db00884b3f42f164931e8cfafd7cc48263cad1361a1d5

Julian's F-Droid Repo (Proton, GrapheneOS)
https://julianfairfax.gitlab.io/fdroid-repo/fdroid/repo?fingerprint=561AD800D900CA8EBF3A531C6A860B5AB8569D0D376FD121CBCCFCA9434D7DF7

**Comment by Iamlooker** [comment]
I have added all of these repos but I wont be adding any repo which require authentication. Those should be added by users.
I also skipped those whose site was unreachable for the moment

**Comment by trytomakeyouprivate** [comment]
awesome thank you!
