### ISSUE TITLE
Community channel 

### ISSUE THREAD

**Issue by Turhvjbufv** [Droid-ify/client#357]
There is no way to contact you except github and email but, when someone has questions or just wants to ask something that's considered small, it's a bit of a shame that there is no easy way to get to you, so I'm suggesting a telegram channel, (I know you have one already but this one's different) that everyone can send a message and ask questions and you or someone who knows the answer can easily answer them

**Comment by Sudeepxl20** [comment]
Telegram group https://telegram.me/droidifyc
