### ISSUE TITLE
[BUG] Material GUI main action button sometimes blocks view

### ISSUE THREAD

**Issue by drws** [Droid-ify/client#361]
**Describe the bug**

Material GUI main action button (in the lower-right part of the screen) sometimes blocks important information displayed on screen. An example of this is the _Installed_ tab where version of the last app in the list is **always** partially covered by the _go to top_ button. Another is the _Repositories_ submenu containing a list with each entry also having a checkmark at the right side to display its status. While the repository can be toggled by touching anywhere in the entry's area, the status is only displayed by the checkmark. And the last entry in the list has its checkmark **always** covered by the _add repository_ button.

**To Reproduce**

1. Open _Repositories_ (sub)menu.
2. Scroll until the end of the list.
3. If you try to determine the status of the last item in the list, it is covered (blocked) by the main action button.

**Expected behavior**

GUI items should be visually separated at least in some scrollable states. The best solution is probably to add some scrollable padding at the bottom of the list (so the button can be put out of the way). This way the last item can also be scrolled a bit further up the screen, making it more accessible. There are other possible solution, but they raise a question about effective amount of screen estate needed for the button and viability of current Material approach.

**Screenshots**

![image](https://github.com/Droid-ify/client/assets/1191893/f30a2303-5e68-4ff2-a784-1b35397147ce)

**Comment by Iamlooker** [comment]
Known and will be fixed in next release.
