### ISSUE TITLE
Repeated applications 

### ISSUE THREAD

**Issue by gallegonovato** [Droid-ify/client#364]
Good afternoon @Iamlooker 

On the main screen of Droid-ify, sometimes I get duplicate apps.

For example: https://ibb.co/5GSk7Ch

The first F-droid is from the Fdroid repository and it puts me as suggested version 1.16.4 . But it comes up with version 1.17-Alpha2

And the second F-droid is from the same repository. But I get suggested alpha2 version.

Both of them are from org.fdroid.basic

I don't have activated to use unstable or beta versions.

Other times it happens to me that an application is in the repository of Fdroid and Izzy. And it only allows me to use the one from a specific repository.

The same thing happens to me using the magnifying glass (the search engine).

I have the latest version of Droid-ify

Best regards and thanks for your time

**Comment by Iamlooker** [comment]
This has nothing to do with our app, the providers provides the app in different package names and we cannot merge them for obvious reasons.
