### ISSUE TITLE
Might you raise the repo list a little in order to properly view the tick sign, please?

### ISSUE THREAD

**Issue by serrq** [Droid-ify/client#381]
Android 13
OnePlus CPH2399
Droid-ify 0.5.7

![1000036435](https://github.com/Droid-ify/client/assets/113377431/ce78a9f5-e853-46cd-bb5c-2f842676db89)

**Comment by GameOverFlowChart** [comment]
I had the same issue, seems to be independent of device.

**Comment by Iamlooker** [comment]
yes, this is known and will be fixed in next release

**Comment by Iamlooker** [comment]
Duplicate of #361
