### ISSUE TITLE
[Crash] Too many favorites?

### ISSUE THREAD

**Issue by Erpe7** [Droid-ify/client#385]
The app is crashing everytime I scroll in the "favourites" menu. I have a lot of apps in here, that's probably why the app is crashing.

0. Have a lot of favourites (can't count how much you need)
1. Go to 'favourites'
2. Scroll down and...
3. See the crash.

 - Device: Xiaomi Mi11 (Venus)
 - OS: Evolution X Android 13
 - Version 7.6.2 | Tapsilog | venus | OFFICIAL, 4.3CPL2-26.1-15406.141207_1008_8fdfc4a93af

**Comment by uli-on** [comment]
The fix will be in the next version: #336

**Comment by Erpe7** [comment]
> The fix will be in the next version: #336

Thank you.
