### ISSUE TITLE
[BUG] app closes after searching manually for updates

### ISSUE THREAD

**Issue by RainerMathey** [Droid-ify/client#418]
**Describe the bug**
... when i go on the wheel in upper right to synchronize the repos and the synchronization is finished, the app closes automatically and i must restart the app to look if there are updates.

**Smartphone (please complete the following information):**
 - Xiaomi Mi 11
 - OS: Android 13
 - MIUI 14.0.3

**Comment by Shocoo** [comment]
Same

**Comment by Iamlooker** [comment]
This is caused by Fluffy Repository, both nightly and stable.

Disabling those should fix this. Seems like their repository is down completely.

**Comment by Iamlooker** [comment]
Fixed with f89bdcf40affd82fe9afbe7595cafc601e7f4b5d
