### ISSUE TITLE
[Crash]The app craches when try to sync repositories 

### ISSUE THREAD

**Issue by Manish8580kumar** [Droid-ify/client#423]
**Describe the bug**
When i try to sync the repositories the app craches in middle of the sync every time

**To Reproduce**
1. Sync repositories
2. After some repositories are sync
3. The app craches at the middle of syncing process

**Smartphone (please complete the following information):**
 - Device: [e.g. redmi 11 prime 4g]
 - OS: [e.g. Android 13]
 - Version [e.g. v0.5.7]

**Comment by Iamlooker** [comment]
Known and fixed with next update. Which will be live tomorrow. You van test alpha builds on telegram group.
