### ISSUE TITLE
Droidify crashing

### ISSUE THREAD

**Issue by slightly-seasoned** [Droid-ify/client#425]
Droidify fails to start after installation on version 0.5.8. The previous version work fine.

**Smartphone:**  
 - Device: Samsung Galaxy S6
 - OS: Android 7.0 (Stock ROM)

**Comment by Drangonfly30** [comment]
I'm also having same issue with android 7.0.

**Comment by Iamlooker** [comment]
This is fixed and will be available in 2 days. Testing build is live on telegram channel

**Comment by WhiCCX0** [comment]
log：https://paste.crdroid.net/ZdovN7

**Comment by Iamlooker** [comment]
> log：https://paste.crdroid.net/ZdovN7

Fixed and will be available in next update, check for test builds on telegram channel.
