### ISSUE TITLE
[BUG] App Crashes When Selecting Update All

### ISSUE THREAD

**Issue by jj49er** [Droid-ify/client#443]
**Describe the bug**
After last update to 0.5.8.1 app closes/crashes when selecting the "Update All" button. 

**Smartphone:**
 - Device: [LG K92]
 - OS: [Android 12]
 - Version [e.g. v0.5.8.1]

**Additional context**
Update All feature was working before the last update.

**Comment by Iamlooker** [comment]
Check new update
