### ISSUE TITLE
[BUG] Crash when hitting the Update All button

### ISSUE THREAD

**Issue by walrus543** [Droid-ify/client#444]
**Describe the bug**
You should have at least 2 apps to update.
The app crashes when hittint the Update button to run the update process for all the apps.

**To Reproduce**
1. Go to the 'Updates' tab
2. Hit the 'Update' button

**Expected behavior**
All updates are downloaded and applied

**Smartphone (please complete the following information):**
 - Device: OnePlus 8 Pro Global
 - OS: OxygenOS Android 13
 - Version: 0.5.8.1(581)

**Additional context**
Settings:
* Disabled: Auto update apps / Unstable updates / Incompatible versions
* Installer: Root Installer (the crash happends right after hitting the download button so I don't think this option is important)
* I can upload a log if necessary. I have no update left for the moment.

**Comment by Iamlooker** [comment]
0.5.8.2 is available. This should be fixed in that.
