### ISSUE TITLE
[BUG] Update everything button no longer works after update

### ISSUE THREAD

**Issue by JVT038** [Droid-ify/client#445]
**Describe the bug**
When clicking on the 'update everything' button, the app crashes.

**To Reproduce**
1. Go to the update tab.
2. Click on update everything.
3. See error

**Expected behavior**
I expected all the apps to be updated to the latest version.

**Smartphone (please complete the following information):**
 - Device: Fairphone 4
 - OS: Android 2
 - Version 0.5.8.1

**Additional context**
This is the logs from logcat:

```
08-24 12:04:17.141  6513  6513 E AndroidRuntime: FATAL EXCEPTION: main
08-24 12:04:17.141  6513  6513 E AndroidRuntime: Process: com.looker.droidify, PID: 6513
08-24 12:04:17.141  6513  6513 E AndroidRuntime: java.lang.IllegalStateException
08-24 12:04:17.141  6513  6513 E AndroidRuntime:        at com.looker.droidify.service.DownloadService.publishForegroundState(SourceFile:209)
08-24 12:04:17.141  6513  6513 E AndroidRuntime:        at com.looker.droidify.service.DownloadService$onCreate$2$2.emit(SourceFile:1)
08-24 12:04:17.141  6513  6513 E AndroidRuntime:        at com.looker.droidify.service.DownloadService$onCreate$2$2$emit$1.invokeSuspend(Unknown Source:12)
08-24 12:04:17.141  6513  6513 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
08-24 12:04:17.141  6513  6513 E AndroidRuntime:        at io.ktor.http.UrlKt.resume(SourceFile:1)
08-24 12:04:17.141  6513  6513 E AndroidRuntime:        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(SourceFile:138)
08-24 12:04:17.141  6513  6513 E AndroidRuntime:        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(SourceFile:45)
08-24 12:04:17.141  6513  6513 E AndroidRuntime:        at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(SourceFile:26)
08-24 12:04:17.141  6513  6513 E AndroidRuntime:        at androidx.work.Worker$2.run(SourceFile:18)
08-24 12:04:17.141  6513  6513 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
08-24 12:04:17.141  6513  6513 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
08-24 12:04:17.141  6513  6513 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
08-24 12:04:17.141  6513  6513 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
08-24 12:04:17.141  6513  6513 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7870)
08-24 12:04:17.141  6513  6513 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-24 12:04:17.141  6513  6513 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-24 12:04:17.141  6513  6513 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)08-24 12:04:17.141  6513  6513 E AndroidRuntime:        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8aa6a46, Dispatchers.Main]
```

**Comment by nussbaumer** [comment]
Still crashing with Version 0.5.8.2
logcat:

> 08-24 20:07:41.856 E/AndroidRuntime(5197): FATAL EXCEPTION: main
08-24 20:07:41.856 E/AndroidRuntime(5197): Process: com.looker.droidify, PID: 5197
08-24 20:07:41.856 E/AndroidRuntime(5197): java.lang.IllegalStateException
08-24 20:07:41.856 E/AndroidRuntime(5197): 	at com.looker.droidify.service.DownloadService.publishForegroundState(SourceFile:209)
08-24 20:07:41.856 E/AndroidRuntime(5197): 	at com.looker.droidify.service.DownloadService$onCreate$2$2.emit(SourceFile:1)
08-24 20:07:41.856 E/AndroidRuntime(5197): 	at com.looker.droidify.service.DownloadService$onCreate$2$2$emit$1.invokeSuspend(Unknown Source:12)
08-24 20:07:41.856 E/AndroidRuntime(5197): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
08-24 20:07:41.856 E/AndroidRuntime(5197): 	at kotlin.text.RegexKt.resume(SourceFile:1)
08-24 20:07:41.856 E/AndroidRuntime(5197): 	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(SourceFile:138)
08-24 20:07:41.856 E/AndroidRuntime(5197): 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(SourceFile:45)
08-24 20:07:41.856 E/AndroidRuntime(5197): 	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(SourceFile:26)
08-24 20:07:41.856 E/AndroidRuntime(5197): 	at androidx.work.Worker$2.run(SourceFile:18)
08-24 20:07:41.856 E/AndroidRuntime(5197): 	at android.os.Handler.handleCallback(Handler.java:942)
08-24 20:07:41.856 E/AndroidRuntime(5197): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-24 20:07:41.856 E/AndroidRuntime(5197): 	at android.os.Looper.loopOnce(Looper.java:201)
08-24 20:07:41.856 E/AndroidRuntime(5197): 	at android.os.Looper.loop(Looper.java:288)
08-24 20:07:41.856 E/AndroidRuntime(5197): 	at android.app.ActivityThread.main(ActivityThread.java:7930)
08-24 20:07:41.856 E/AndroidRuntime(5197): 	at java.lang.reflect.Method.invoke(Native Method)
08-24 20:07:41.856 E/AndroidRuntime(5197): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-24 20:07:41.856 E/AndroidRuntime(5197): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
08-24 20:07:41.856 E/AndroidRuntime(5197): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8e14dd2, Dispatchers.Main]

**Comment by adarsh1001** [comment]
+1, updated to patch 2 but still crashing.

**Comment by Iamlooker** [comment]
This is under active testing in the [Telegram Group](https://t.me/droidifyc). You can help with testing in the group as we are lacking testers.

**Comment by Iamlooker** [comment]
Fixed in Patch 3 and also tested by many users
