### ISSUE TITLE
I have a question regarding suggestions made by droid-ify when more than one repository are active for same app ?

### ISSUE THREAD

**Issue by Wolverine0789** [Droid-ify/client#450]
So I have mull browser (not installed) which has two repositories (f-droid & divest os official), why does droid-ify suggests f-droid repository which receives updates later than divest os official ? Is it how it is supposed to behave or is it a bug ?

![Screenshot_2023-08-27-16-36-29-706_com.looker.droidify.jpg](https://github.com/Droid-ify/client/assets/98686009/0d037ade-433b-4633-a235-cd3587bc71d9)

**Comment by Iamlooker** [comment]
We suggest the most recent release. In this case it is FDroid release.
