### ISSUE TITLE
Question - What method is recommended for updating the client app?

### ISSUE THREAD

**Issue by hl2guide** [Droid-ify/client#451]
What method is recommended for updating the client app?

I always get the error:

```
App not installed as package conflicts with an existing package.
```

I'm using a Samsung smart phone, if that's relevant.

**Comment by Iamlooker** [comment]
What version are you using currently?

**Comment by hl2guide** [comment]
@Iamlooker 0.5.7

**Comment by Iamlooker** [comment]
I would suggest that you use GitHub releases for fastest updates. Using FDroid releases is also fine but they provide updates a little later.
