### ISSUE TITLE
[Crash] Updating large app crashes droid-ify on both of my devices

### ISSUE THREAD

**Issue by unoukujou** [Droid-ify/client#452]
**Describe the bug**
When I update Mulch from DivestOS repository, droid-ify crashes. Happens on both my devices, galaxy and pixel.

**To Reproduce**
Download and update Mulch from DivestOS repo.

**Smartphone (please complete the following information):**
 Pixel and samsung galaxy, both.

**Additional context**
All settings pretty much default

**Comment by Iamlooker** [comment]
Droidify version?

**Comment by Iamlooker** [comment]
Droidify version?

**Comment by unoukujou** [comment]
> Droidify version?

It's this one:

Release 0.5.8 Patch 3
https://github.com/Droid-ify/client/releases/download/v0.5.8.3/app-release.apk

**Comment by Iamlooker** [comment]
Similar to #475
