### ISSUE TITLE
[BUG] Maximized screenshots block navigation bar

### ISSUE THREAD

**Issue by bege10** [Droid-ify/client#456]
**Describe the bug**
Maximized screenshots block navigation bar

**To Reproduce**
1. Go to app details
2. Click on a screenshot
3. Navigation bar is covered and cannot be reached

**Expected behavior**
Navigation bar still accessible

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Fairphone 3
 - OS: /e/OS S (Android 12)
 - Version [e.g. v0.5.8.3]

**Additional context**

**Comment by Iamlooker** [comment]
Duplicate of #322
