### ISSUE TITLE
[BUG] Droidify no longer detecting Sui

### ISSUE THREAD

**Issue by KenJyn76** [Droid-ify/client#460]
**Describe the bug**
After the Shizuku API update, Droidify can no longer get access from Sui, despite it being granted. 

**To Reproduce**
Install latest sui v13.5.0
Install Droidify
Select Shizuku installer
See "Shizuku not installed"

**Expected behavior**
Droidify should get a prompt for access from Sui, or be granted access if it is already granted. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 13
 - Version: 0.5.8.3

**Additional context**
This worked in the last release, and still does if I roll back to it with the same sui version.

Log:
`01.09 16:25:15.646 10289 21214 21214 com.looker.droidify I/looker.droidify: Using CollectorTypeCC GC.
01.09 16:25:15.649 10289 21214 21214 com.looker.droidify E/looker.droidify: Not starting debugger since process cannot load the jdwp agent.
01.09 16:25:15.668 10289 21214 21214 com.looker.droidify D/CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10289; state: ENABLED
01.09 16:25:15.674 10289 21214 21214 com.looker.droidify D/nativeloader: Configuring classloader-namespace for other apk /data/app/~~AT-v8gfYP7h7uziTYmFYkg==/com.looker.droidify-j5a9N4hWkK_H87FCdzyY0w==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~AT-v8gfYP7h7uziTYmFYkg==/com.looker.droidify-j5a9N4hWkK_H87FCdzyY0w==/lib/arm64, permitted_path=/data:/mnt/expand:/data/user/0/com.looker.droidify
01.09 16:25:15.683 10289 21214 21214 com.looker.droidify V/GraphicsEnvironment: ANGLE Developer option for 'com.looker.droidify' set to: 'default'
01.09 16:25:15.683 10289 21214 21214 com.looker.droidify V/GraphicsEnvironment: ANGLE GameManagerService for com.looker.droidify: false
01.09 16:25:15.683 10289 21214 21214 com.looker.droidify V/GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
01.09 16:25:15.684 10289 21214 21214 com.looker.droidify D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
01.09 16:25:15.685 10289 21214 21214 com.looker.droidify D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
01.09 16:25:15.691 10289 21214 21214 com.looker.droidify D/WM-WrkMgrInitializer: Initializing WorkManager with default configuration.
01.09 16:25:15.696 10289 21214 21214 com.looker.droidify I/ShizukuApplication: attachApplication
01.09 16:25:15.696 10289 21214 21214 com.looker.droidify D/ShizukuProvider: Initialize Sui: true
01.09 16:25:15.705 10289 21214 21214 com.looker.droidify W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
01.09 16:25:15.705 10289 21214 21214 com.looker.droidify W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
01.09 16:25:15.705 10289 21214 21214 com.looker.droidify W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
01.09 16:25:15.713 10289 21214 21229 com.looker.droidify D/CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10289; state: ENABLED
01.09 16:25:15.720 10289 21214 21229 com.looker.droidify D/CompatibilityChangeReporter: Compat change id reported: 194532703; UID 10289; state: ENABLED
01.09 16:25:15.818 10289 21214 21241 com.looker.droidify W/JobInfo: Requested flex +5m0s0ms for job 1 is too small; raising to +36m0s0ms
01.09 16:25:15.820 10289 21214 21237 com.looker.droidify I/CleanUpWorker: Periodic work enqueued with duration: 12h
01.09 16:25:15.859 10289 21214 21214 com.looker.droidify D/CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10289; state: ENABLED
01.09 16:25:15.861 10289 21214 21214 com.looker.droidify D/CompatibilityChangeReporter: Compat change id reported: 210923482; UID 10289; state: ENABLED
01.09 16:25:15.901 10289 21214 21214 com.looker.droidify D/CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10289; state: DISABLED
01.09 16:25:16.018 10289 21214 21214 com.looker.droidify W/View: requestLayout() improperly called by androidx.appcompat.view.menu.ActionMenuItemView{a4e51be VFED..C.. ......ID 0,10-127,136 #7f0801f4 app:id/toolbar_search} during layout: running second layout pass
01.09 16:25:16.019 10289 21214 21214 com.looker.droidify W/View: requestLayout() improperly called by androidx.appcompat.view.menu.ActionMenuItemView{734e21f VFED..CL. ......ID 127,10-254,136 #0} during layout: running second layout pass
01.09 16:25:16.019 10289 21214 21214 com.looker.droidify W/View: requestLayout() improperly called by androidx.appcompat.widget.ActionMenuView{163e96c V.E...... ......ID 721,10-1080,157} during layout: running second layout pass
01.09 16:25:16.019 10289 21214 21214 com.looker.droidify W/View: requestLayout() improperly called by android.widget.FrameLayout{e317b35 VFE...C.. ......ID 0,126-1080,126 #7f0801a0 app:id/section_layout} during layout: running second layout pass
01.09 16:25:16.065 10289 21214 21237 com.looker.droidify I/CleanUpWorker: doWork: Started Cleanup
01.09 16:25:16.070 10289 21214 21234 com.looker.droidify I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=c43dd576-e770-4bf4-b9c4-1fc6f684e18d, tags={ com.looker.droidify.work.DelegatingWorker } ]
01.09 16:25:17.880 10289 21214 21214 com.looker.droidify W/OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
01.09 16:25:17.880 10289 21214 21214 com.looker.droidify W/OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
01.09 16:25:17.933 10289 21214 21214 com.looker.droidify W/PropertyValuesHolder: Method set() with type float not found on target class class androidx.coordinatorlayout.widget.CoordinatorLayout
01.09 16:25:17.933 10289 21214 21214 com.looker.droidify W/PropertyValuesHolder: Method get() with type null not found on target class class androidx.coordinatorlayout.widget.CoordinatorLayout
01.09 16:25:17.933 10289 21214 21214 com.looker.droidify W/PropertyValuesHolder: Method setPercentTranslationY() with type float not found on target class class androidx.coordinatorlayout.widget.CoordinatorLayout
01.09 16:25:18.189 10289 21214 21238 com.looker.droidify D/OpenGLRenderer: endAllActiveAnimators on 0xb40000728c4f08c0 (MenuPopupWindow$MenuDropDownListView) with handle 0xb40000719c491170
01.09 16:25:20.115 10289 21214 21214 com.looker.droidify I/AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
01.09 16:25:20.930 10289 21214 21272 com.looker.droidify D/ProfileInstaller: Skipping profile installation for com.looker.droidify
01.09 16:25:21.059 10289 21214 21238 com.looker.droidify D/OpenGLRenderer: endAllActiveAnimators on 0xb40000728c50c4f0 (AlertController$RecycleListView) with handle 0xb40000719c4a11c0
01.09 16:25:21.068 10289 21214 21214 com.looker.droidify W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
01.09 16:25:28.772 10289 21214 21222 com.looker.droidify W/looker.droidify: Cleared Reference was only reachable from finalizer (only reported once)`

**Comment by jarkad** [comment]
This happens to me too after last update.

- Device: Moto G60
- OS: LineageOS 20 (Android 13)
- Version: 0.5.8.3

**Comment by Iamlooker** [comment]
Will fix this in next patch on Tuesday

**Comment by Iamlooker** [comment]
I will be releasing an alpha on telegram channel. Can you join and test it please.

I don't have Sui so I can't test it.

**Comment by Iamlooker** [comment]
Fixed in 96ee027d902ce2e550ef3a35e544851b1368872f
