### ISSUE TITLE
[BUG] can not change app language to chinese

### ISSUE THREAD

**Issue by lbwstco** [Droid-ify/client#462]
**Describe the bug**
Missing Chinese in App Language of System Settings
In App Setting, when I choose 中文(中国), it always show Rcn.

**To Reproduce**
In Droidify:
1. Go to 'Settings'
2. Click on 'Language'
3. Select '中文(中国)'
4. It shows 'Rcn', and app language is still English. (screenshot 1)

In System Settings:
1. Go to 'App languages'
2. no 'Chinese' option show (screenshot 2)

**Expected behavior**
set app language to chinese.

**Screenshots**
![image](https://github.com/Droid-ify/client/assets/6779378/49b9ac20-396e-43cf-b01c-280efe6c4ace)
![image](https://github.com/Droid-ify/client/assets/6779378/49f1300c-90f7-4d60-bdae-cd0bb782cee1)

**Smartphone (please complete the following information):**
 - Device:  Samsung Note20 Ultra
 - OS: Android 13 OneUI 5.1
 - Version: 0.5.8.3

**Additional context**

**Comment by Iamlooker** [comment]
Ooh thats weird. I will try and fix this

**Comment by Iamlooker** [comment]
Fixed with 0ac09a9eccfb4c2f40cd85821198ddeae69ae3c5
