### ISSUE TITLE
[BUG] Suspicious calls to https://f-droid.org/repo/null

### ISSUE THREAD

**Issue by papjul** [Droid-ify/client#466]
**Describe the bug**
Using a HTTP interceptor, I can see calls to https://f-droid.org/repo/null

**To Reproduce**
1. Go to main app
2. Scroll
3. HTTP calls are made to https://f-droid.org/repo/null

**Expected behavior**
If a value is null, it should be ignored and not make a HTTP call.

**Screenshots**
Not relevant.

**Smartphone (please complete the following information):**
Not relevant.

**Additional context**
It seems to happen when icon for the app is not defined in F-Droid repo.

**Comment by papjul** [comment]
I don't have any log, I'm using an external HTTP interceptor that is showing me all HTTP calls made by apps on my Android device. And I can see as I scroll the Droid-ify app that it is making tons of calls to this https://f-droid.org/repo/null URL among other URLs that are icons.

If you want to see by yourself (and be sure that you indeed fix the problem) and you have root available by adb, you can use this software for example:
https://httptoolkit.com/

Otherwise, as you seem to use OkHttp, you can also add HttpLoggingInterceptor on your debug builds (not on releases, of course) so you can see every HTTP calls made: https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor

**Comment by Iamlooker** [comment]
Can you test alpha build in the Telegram Group: https://t.me/droidifyc
