### ISSUE TITLE
Clarification on Folder Structure for Icons

### ISSUE THREAD

**Issue by FixFlare** [Droid-ify/client#470]
I'm trying to run my own custom fdroid repo and my icons are not displaying with droid-ify but they work just fine with the regular f-droid client.

I'm hoping I can get some clarification on the proper structure to work with droid-ify.

When I ran fdroid init it creates it in this structure:

```bash
├── fdroid
│   ├── config.yml
│   ├── keystore.p12
│   ├── metadata
│   │   ├── com.myapp.yml
│   ├── repo
│   │   ├──com.myapp.apk
│   │   ├── entry.jar
│   │   ├── entry.json
│   │   ├── icons
│   │   │    └──com.myapp.1539440064.png
│   │   ├── icons-120
│   │   │    └──com.myapp.1539440064.png
│   │   ├── icons-160
│   │   │    └── com.myapp.1539440064.png
│   │   ├── icons-240
│   │   │    └──com.myapp.1539440064.png
│   │   ├── icons-320
│   │   │    └──com.myapp.1539440064.png
│   │   ├── icons-480
│   │   │    └──com.myapp.1539440064.png
│   │   ├── icons-640
│   │   │    └──com.myapp.1539440064.png
│   │   ├── index-v1.jar
│   │   ├── index-v1.json
│   │   ├── index-v2.json
│   │   ├── index.css
│   │   ├── index.html
│   │   ├── index.jar
│   │   ├── index.png
│   │   ├── index.xml
│   │   └── status
│   │       ├── running.json
│   │       └── update.json
```

And there doesn't seem to be any mention of all the extra icon folders on this page: [https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/)

I tried adding this to my structure and running "fdroid update" but it still doesn't show my icons in droid-ify.

```bash
├── fdroid
│   ├── config.yml
│   ├── keystore.p12
│   ├── metadata
│   │   ├── com.myapp.yml
│   ├── repo
>>added
│   │   ├──com.myapp.apk
│   │   ├── com.myapp
│   │   │   └── en-US
│   │   │        └──icon.png
...
```

Can anyone point me to what I am doing wrong?

Thanks in advance,

**Comment by Iamlooker** [comment]
Sorry I have no experience with building FDroid repository. Maybe someone in the community can help.

**Comment by FixFlare** [comment]
Appreciate the quick reply-

Any chance you can fill me in on how droidify builds the URL for the icons? I think I may be able to solve it if I knew that.

I've been looking at the source code and it looks like it uses the v1 index - here is an example of what mine looks like


```bash
{
    "repo": {
        "timestamp": 1694072254000,
        "version": 20002,
        "name": "My Custom Repo",
        "icon": "icon.png",
        "address": "https://mydomain.com/fdroid/repo",
        "description": "My Custom Repo!"
    },
    "requests": {
        "install": [],
        "uninstall": []
    },
    "apps": [
        {
            "categories": [
                "repo"
            ],
            "suggestedVersionCode": "21237",
            "license": "Unknown",
            "name": "MyApp",
            "added": 1694064222000,
            "icon": "com.myapp.1539440064.png",
            "packageName": "com.myapp",
            "lastUpdated": 1694061322000,
            "localized": {
                "en-US": {
                    "icon": "icon_NnwHpi14-n0CU-xQHHibglGsj7YuLQGF7TjJQXrxvtA=.png"
                }
            }
        }
    ],
...
}
```


In the "icon" field there is just the filename, no folder name, so in order for droid-ify to find the icon it would need to be concatenating repo.address + "/icons/" + icon value from the v1 index.


e.g.

This does NOT work: https://mydomain.com/fdroid/repo/com.myapp.1539440064.png


This works: https://mydomain.com/fdroid/repo**/icons/**com.myapp.1539440064.png


Thanks,

**Comment by ShareASmile** [comment]
Not sure but maybe @IzzyOnDroid can put some  light on the issue!

**Comment by IzzySoft** [comment]
index-v1 has just the file name there, correct (index-v2 has a leading `/` for reasons I never fully understood). The path to icons depends on whether they were taken from "fastlane" of extracted from the APK. IIRC, "no path" means the former, in which case the icons reside in `repo/<packageName>/<locale>/images/`; otherwise the value starts with `/icons` (index-v2; I have no time to dig it up completely now) and refers to `repo/icons/`.

The file name of the icon in your example rather looks like one from the metadata ("fastlane"), which confirms the above. As pointed out, I currently lack the time to look this up in detail, sorry.

**Comment by FixFlare** [comment]
Thanks all for the comments and feedback but I think I may have found the problem.

I ran a packet capture on my phone to see where the icons were being pulled from and where it was failing.

Turns out, I was getting a 401 unauthorized when droid-ify was trying to pull the icons.

It would appear to me, if you use authentication on your repo, droid-ify is not sending the authentication information as part of the request to retrieve the icons.


I tested 3 other clients with my same repo, they all work fine, it is only Droid-ify that has this issue.

All these clients work fine with authentication:

Neo Store
F-Droid Official Client
Foxy Droid


Curiously enough, I disabled authentication on my nginx server, then the icons came through just fine on Droid-ify.
I then re-enabled authentication and the icons remained. I thought they're probably cached so I first cleared cache, could still see the icons, then I cleared data storage, can still see the icons. I'm not sure why that is.


I then tested a second android phone that had never installed droid-ify before and it had the same issue -  after adding the repo with authentication, the icons do not show.

Pretty sure this is a bug.

**Comment by Iamlooker** [comment]
Ooh. I will fix this issue in the next release.

**Comment by Iamlooker** [comment]
Fixed with e24468df8cb8c94e24b6115688e925b2a52a6fac

**Comment by Iamlooker** [comment]
You can test this in the alpha build in the telegram group or by using debug build from the [Actions](https://github.com/Droid-ify/client/actions) tag

**Comment by FixFlare** [comment]
> You can test this in the alpha build in the telegram group or by using debug build from the [Actions](https://github.com/Droid-ify/client/actions) tag

Just tested the latest debug APK and can confirm both the icons as well as the input suggestion issues are fixed.

Appreciate the quick turn around on that. 👍
