### ISSUE TITLE
Strange servers' answers (screenshot)

### ISSUE THREAD

**Issue by serrq** [Droid-ify/client#471]
Sometimes some repos show this error: when it usually happens after a few seconds the problem resolves itself.

Today I had to close Droid-ify killing the process because the popup did not close even pressing "cancel".

Why is this situation happening?

![1000040383](https://github.com/Droid-ify/client/assets/113377431/4678cfef-6596-4c38-9cc5-c7db27681da5)

**Comment by Iamlooker** [comment]
This should be fixed is last few releases, can you check
