### ISSUE TITLE
Crash after cancelling download [BUG]

### ISSUE THREAD

**Issue by NeuronsReact** [Droid-ify/client#472]
**Describe the bug**
If I start downloading an APK then cancel it, the client will crash after about 10 seconds.

**To Reproduce**
1. Pick an app and click on 'Install' to install an app
2. Click on 'cancel' before download complete
3. Wait for 10 seconds
4. See the client crash without any error message

**Expected behavior**
The client should behave normally without crash.

**Smartphone (please complete the following information):**
 - Device: [Realme 7 5G (RMX2117)]
 - OS: [Android 12]
 - Version [v0.5.8.3 and v0.5.8.4]

**Comment by Iamlooker** [comment]
Can you test alpha build in the Telegram Group: https://t.me/droidifyc

**Comment by NeuronsReact** [comment]
> Can you test alpha build in the Telegram Group: https://t.me/droidifyc

Thanks. It seems fixed in the alpha build.
