### ISSUE TITLE
Not added repo in TOR network addresses

### ISSUE THREAD

**Issue by userkilled** [Droid-ify/client#483]
The application, when the proxy is enabled, writes that the address is incorrect and the address is not available.
Version app: 5.8.4

**Comment by Iamlooker** [comment]
Please provide the repo name and address

**Comment by userkilled** [comment]
http://anonero5wmhraxqsvzq2ncgptq6gq45qoto6fnkfwughfl4gbt44swad.onion/fdroid/repo?fingerprint=C5705FF724538F6925B6093517F53C6C6BB6CF82518ED40EB4B8CBBB87DC0D1D

http://rk63tc3isr7so7ubl6q7kdxzzws7a7t6s467lbtw2ru3cwy6zu6w4jad.onion/fdroid/repo?fingerprint=0C72C540E5841030FAE32329A1BC8747DCAC5236E4D1AAEDB67735CA7B7DD3D6

**Comment by Iamlooker** [comment]
Are you sure `Tor Service` is running?

**Comment by userkilled** [comment]
Yes, i used InviZible Pro proxy mode.
Sock 9051 http 8081

**Comment by userkilled** [comment]
F-Droid Classic sync this repos

**Comment by Iamlooker** [comment]
Can you test this in alpha build

You can download the latest alpha builds from our [Telegram Community](https://t.me/droidifyc) or [Actions Tab](https://github.com/Droid-ify/client/actions/workflows/build_debug.yml)

**Comment by userkilled** [comment]
> Can you test this in alpha build
> 
> You can download the latest alpha builds from our [Telegram Community](https://t.me/droidifyc) or [Actions Tab](https://github.com/Droid-ify/client/actions/workflows/build_debug.yml)

It's great work

**Comment by userkilled** [comment]
Thx
