### ISSUE TITLE
Make the “Versions” section on the application page collapsible

### ISSUE THREAD

**Issue by topminipie** [Droid-ify/client#488]
Make the “Versions” section on the application page collapsible like the “Permissions” and “Links” sections.

**Comment by Iamlooker** [comment]
Sorry but this doesn't make any sense in my opinion. What benefit would it provide?

Having versions list visible makes it easy to see updates, release date, etc...

Even if i make it collapsable I will keep it expanded by default. Which destroys the point.

**Comment by Iamlooker** [comment]
If you have a reason behind this you can reopen this issue, or tag me
