### ISSUE TITLE
[BUG] Using sui instead of shizuku causes installer type to rapidly swap (Installing still works.)

### ISSUE THREAD

**Issue by AntiCheatv4** [Droid-ify/client#490]
**Describe the bug**
When using sui the installer selector visually switches between shizuku and session installer.
The bug does not happen when shizuku is installed
installing apps through sui still works

**To Reproduce**
1. Install the magisk module sui
2. Set installer to shizuku and allow with sui
3. Installer type will rapidly switch between session and shizuku

**Expected behavior**
Installer selection stays on shizuku.

**Screenshots**
https://github.com/Droid-ify/client/assets/91042765/3d1aed63-ee55-4253-9d30-475af4d2f8d9

**Smartphone (please complete the following information):**
 - Device: [Oneplus 7 pro]
 - OS: [Lineage OS for microG]
 - Version [e.g. v0.5.9]

**Comment by Iamlooker** [comment]
This has been fixed and will be available around 19:00 IST Wednesday, 27/09

**Comment by Iamlooker** [comment]
You can download the latest alpha builds from our [Telegram Community](https://t.me/droidifyc) or [Actions Tab](https://github.com/Droid-ify/client/actions/workflows/build_debug.yml)
