### ISSUE TITLE
add multiplatform

### ISSUE THREAD

**Issue by N0N3C0D3** [Droid-ify/client#492]
what I mean is to add multiplatform support for example windows and so on plus there could be games and other things like krita, davinci resolve and vlc which are just a few examples.

**Comment by meenbeese** [comment]
I think with the deprecation of WSA, this proposal is out of scope for Droid-ify, right? It already would have required tremendous work before that, and now it requires even more with little to no apparent benefit. @Iamlooker wdyt?

**Comment by Iamlooker** [comment]
True @meenbeese, that being said I am a solo developer working on this in my free time so it is tough to find motivation to even work on small stuff and this is basically a whole new project. I don't think I will be able to fulfill this in foreseeable future

**Comment by meenbeese** [comment]
No one can judge you when you have worked so hard on a FOSS application and delivered an awesome experience. I completely understand how difficult it can be to find motivation for such a large project and want to thank you for that. Please know that your work is highly valued and appreciated by the community. If there’s anything we can do to support you or if you ever need a break, don’t hesitate to reach out.
