### ISSUE TITLE
[BUG] Potential invalid requests resulting in server DoS

### ISSUE THREAD

**Issue by SkewedZeppelin** [Droid-ify/client#499]
**Describe the bug**
I run the divestos.org F-Droid repositories, my server logs are  filled with invalid requests for the resource `/fdroid/official/null` with the User-Agent okhttp/5.0.0-alpha.11.
This is the same version as was previously declared here: https://github.com/Droid-ify/client/commit/1eb40c3e167f60ca48198588d0172edfeedceb71#diff-df8b4af8cccf28e19228317a74d3fba23fed6c067665f72670b7d4986515ad39L104

**To Reproduce**
1. Enable a DivestOS repo(, and probably any other repo)
2. Swipe between screens
3. Watch invalid requests be made

**Expected behavior**
Not make such invalid requests

**Additional information**
I am not entirely clear if this is actually Droid-ify, it may be Neo-Store, as they use the same okhttp version: https://github.com/NeoApplications/Neo-Store/blob/master/build.gradle.kts#L21
https://github.com/NeoApplications/Neo-Store/issues/522

Given that I haven't seen any of these requests with Ktor in the UA, it is likely Neo-Store.

If this was Droid-ify, is it possible to put out an announcement for users to update their clients via any available channels?

Please also consider declaring your User-Agent as well.

**Comment by Iamlooker** [comment]
Which version of droidify are you using?

As this was fixed in one of the old releases.

**Comment by licaon-kter** [comment]
@Iamlooker OP is not using the client, users of Divest OS are... out of their own free will :)

**Comment by Iamlooker** [comment]
Ooh sorry I didn't read the second half. Sorry.

I will try to announce it in the TG Channel and GitHub announcements. This should probably reach the most amount of people.

Also about declaring a UA, I will surely do it in coming update. 😊

**Comment by SkewedZeppelin** [comment]
Thank you!

**Comment by Iamlooker** [comment]
I have annouced this on GitHub and Telegram. Most people should have updated by now. 😃
