### ISSUE TITLE
[BUG] Install / Update button not working after switching app

### ISSUE THREAD

**Issue by opk12** [Droid-ify/client#501]
**Describe the bug**
If you switch to another app, instead of staying inside Droid-ify while it downloads an app, the Install / Update button does not work.

**To Reproduce**
* Open an app's details page.
* Click the green button Install or Update.
* Switch to another open app.
* Wait until the download finishes.
* Switch back to Droid-ify.
* Click Install or Update.
* Nothing happens.

**Smartphone (please complete the following information):**
0.5.8.3 (current latest) on two Samsung phones (Android 10, Android 7.1).

**Additional context**
If you do **not** switch app, it works.
For example, if you switch to another app details page, while staying inside the Droid-ify app, it works.
Tapping the notification also works.

**Comment by Iamlooker** [comment]
This has been fixed you can try latest release
