### ISSUE TITLE
About icons

### ISSUE THREAD

**Issue by BabyOilJohnson** [Droid-ify/client#506]
Change "back button" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aarrow_back%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "scroll back to top" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aarrow_upward%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "open" icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aopen_in_new%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "app info" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Apage_info%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "uninstall" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Adelete%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "search" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Asearch%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "refresh" icon to[this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Async%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "install" icon to[this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Adownload%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 

In link section,
Change "code" icon to[this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Adownload%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "contact" icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aperson%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "mail" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Amail%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "copyright" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Acopyright%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "bug" icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Abug_report%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "change log" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Ahistory%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "website" icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aglobe%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)

**Comment by Iamlooker** [comment]
This is just to address the rounding right?

**Comment by BabyOilJohnson** [comment]
> This is just to address the rounding right?

Yeah, more materialized.

**Comment by Iamlooker** [comment]
Done
