### ISSUE TITLE
[Crash] Removing root causes crash.

### ISSUE THREAD

**Issue by TheSoulWizard** [Droid-ify/client#510]
When having the install method set to [Root], uninstalling Magisk for example will cause the app to crash every time you try to open it.

-_Removing root permission could also cause the same problem. (**UNTESTED**)_

Clearing cache won't help, you have to clear all data in order to get it working again, which also wipes all repos.

Version: 0.5.8.3
Android: 9 (Pie)
Device Codename: Falcon

**Comment by Iamlooker** [comment]
Try updating to 0.5.9 Patch 1

**Comment by Iamlooker** [comment]
Will mark as complete till you reply
