### ISSUE TITLE
[BUG] Link in the description causes double install and stuck `Cancel` button

### ISSUE THREAD

**Issue by opk12** [Droid-ify/client#514]
**Describe the bug**
Following a link in the app description triggers a spurious installation process and makes the Droid-ify GUI stuck at the installation phase.

**To Reproduce**
* Install [Browser Intercept](https://f-droid.org/en/packages/com.intrications.android.sharebrowser/).
* Wait for installation to complete.
* In the description, click the link `com.nightshadelabs.anotherbrowser`.
* (bad) You are prompted to install again.
* Cancel this second installation.
* Flash-ify opens in Droid-ify.
* Press Back to return to Browser Intercept.
* (bad) The page for Browser Intercept that you return to has the `Cancel` button.
* (bad) Pressing `Cancel` has no effect.

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android 7.1
 - Version: 0.5.9 Patch 1, from the F-droid repo

**Comment by Iamlooker** [comment]
Can you share a video of the bug? I am unable to recreate this.

**Comment by Iamlooker** [comment]
Cannot reproduce
