### ISSUE TITLE
Show Top-App Authors like in g-droid

### ISSUE THREAD

**Issue by user0-tb** [Droid-ify/client#520]
**What feature are you requesting?**
In g-droid there is an Top-App-Authors feature that I like. I would be happy if you add this to droid-ify.

**Describe the solution you'd like**
Adding the Top-App-Authors feature 

**Additional context**
![Screenshot_20231018_150639_org gdroid gdroid_edit_2011009094483](https://github.com/Droid-ify/client/assets/104380885/9f6fdb02-adc9-4abc-a9a0-5ffdb6263e67)
![Screenshot_20231018_150647_org gdroid gdroid](https://github.com/Droid-ify/client/assets/104380885/411c8483-172c-435d-8810-1734fe537d1a)

**Comment by user0-tb** [comment]
It's based on the downloads, I think.

**Comment by Iamlooker** [comment]
Its based on github stars

**Comment by vdbhb59** [comment]
But does this make sense? All I can see is it will increase load on the app, device and bandwidth too. It will also increase app size.
Moreover, for old and low memory phones, it will be beyond overkill.

**Comment by Iamlooker** [comment]
> But does this make sense? All I can see is it will increase load on the app, device and bandwidth too. It will also increase app size.
> Moreover, for old and low memory phones, it will be beyond overkill.

True, and this is beyond the scope of the app's idea
