### ISSUE TITLE
[Crash] Crashing on Android 14 version 0.5.9 Patch 2

### ISSUE THREAD

**Issue by XioR112** [Droid-ify/client#526]
**Describe the bug**
After newest update app started crashing.

**To Reproduce**
For example:
 - clicking refresh button
 - installing any app
 - enabling repository
Causes crash

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - OS: Android 14
 - Version: 0.5.9 Patch 2

**Comment by H-Jonathan** [comment]
I am having the same exact issue.
I'm also on Android 14 but on pixel 7a.

**Comment by xusiai** [comment]
Experiencing this as well on a Pixel 7 Pro with Android 14. Latest apk release from Github.

**Comment by pabloscloud** [comment]
Same. Android 14, pixel 4a (5g).

I'd provide you with a crashlog buy seems like it doesn't provide ond

**Comment by KibSquib48** [comment]
same for me too, Pixel 6
not sure where to find the crash log

**Comment by Privacy-Now** [comment]
Same issue but I'll also add to and say it crashes when I try to update an app too. On a Pixel 5 latest Graphene OS.

**Comment by OldBuffGuy** [comment]
Same issue on Pixel 6 Pro with Android 14.

**Comment by Iamlooker** [comment]
This is fixed and will be available in next release in few hours

**Comment by Iamlooker** [comment]
Fixed in Patch 3
