### ISSUE TITLE
[BUG] Cromite Repo x2

### ISSUE THREAD

**Issue by HarriBuh** [Droid-ify/client#530]
**Describe the bug**

**To Reproduce**
1. Go to "package sources"
2. Recognise there are TWO identical Cromite sources
3. Add both
4.  xxx 

**Expected behavior**
Only one source should be existent and available.

**Screenshots**
xxx

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7
 - OS: Android 14
 - Version xx

**Comment by Iamlooker** [comment]
This has also been fixed and will be available in next release
