### ISSUE TITLE
Material You hasn't the correct on start up; but reset on interaction [BUG]

### ISSUE THREAD

**Issue by Uneccessary** [Droid-ify/client#535]
**Describe the bug**
Video.

**To Reproduce**
1. Open the App
2. Interact with the app by click a app or smth

**Expected behavior**
That the Material You and selected Theme is constantly applied

**Screenshots**

https://github.com/Droid-ify/client/assets/145043411/f0c89f27-b7fa-454d-8d67-44fe032bc75e

**Smartphone (please complete the following information):**
 - Device: [Galaxy A33 5G]
 - OS: [e.g. Android 13]
 - Version [Latest]

**Comment by Iamlooker** [comment]
This has been fixed and will be available in next release

**Comment by Uneccessary** [comment]
Alright thank u!
