### ISSUE TITLE
[Crash]Version 0.5.9 PATCH 2

### ISSUE THREAD

**Issue by wiltet** [Droid-ify/client#538]
**Describe the bug**
-right now I did get the regular update of droid-ify through the app itself to 0.5.9 PATCH 2
-appcrash when selecting the refresh (update) button

**To Reproduce**
1. update
2. update repos

**Smartphone (please complete the following information):**
 - Device: Pixel 7a
 - OS: GrapheneOS Android 14
 - Version: 0.5.9 PATCH 2

**Additional context**
It`s not possible to install a newer version or make a rollback of droid-ify if the app is installed in other profiles simultant.

[appcrash.txt](https://github.com/Droid-ify/client/files/13114396/appcrash.txt)

**Comment by Iamlooker** [comment]
Patch 4 was released some days later hence fdroid servers are a little late to catch upto the updates.

**Comment by wiltet** [comment]
That is a problem, when all the devices getting the buggy release.
After uninstalling droid-ify it is not possible to install it again. Seems to be not uninstalled propperly.

Now the user is in big trouble because the app is not working anymore and reinstall is nit possible.

**Comment by wiltet** [comment]
Is there a solution to get rid of the faulty droid-ify?

**Comment by Iamlooker** [comment]
It looks like you are using Izzy release so you can simply download directly from GitHub release and update no need to uninstall

**Comment by wiltet** [comment]
Now it is uninstalled allready and all other releases wont be installed because a error showing up when starting the installation. No other releases can be reinstalled at the moment! (restart the device does not help)

**Comment by wiltet** [comment]
error: (translated from german)
app couldn`t be installed because it is in conflict with a existing packet

**Comment by Iamlooker** [comment]
> error: (translated from german) app couldn`t be installed because it is in conflict with a existing packet

You might have it installed in another user/work profile

**Comment by wiltet** [comment]
thats maybe the problem, let me check
