### ISSUE TITLE
[BUG] 0.5.9 Patch 2 crashes a lot

### ISSUE THREAD

**Issue by AJCxZ0** [Droid-ify/client#541]
**Describe the bug**
Trying to do almost anything in 0.5.9 Patch 2 causes a crash.

**To Reproduce**
1. Upgrade to 0.5.9 Patch 2 from previous version
2. Launch app
3. Try almost any operation such as sync'ing, changing settings, switching tabs
4. Watch app repeatedly but not 100% consistently crash
5. Stop app, clear cache and clear storage and re-test
6. Observe the same result

**Expected behavior**
App doesn't crash.

**Smartphone (please complete the following information):**
 - Device: Pixel  7
 - OS: Android 14
 - Version: v0.5.9 Patch 2

**Additional context**
Previous version has working perfectly.

**Comment by Iamlooker** [comment]
Update to Patch 4 and please check old issues. I have closed same issue many times.

**Comment by AJCxZ0** [comment]
BTW, the link "[on GitHub](https://github.com/Droid-ify/Droid-ify/issues/new)" on the [Community](https://droidify.eu.org/community) page is 404. It should be to [here](https://github.com/Droid-ify/client/issues/new) .

**Comment by AJCxZ0** [comment]
> Update to Patch 4 and please check old issues. I have closed same issue many times.

Thank you. I saw no open issues, so reported this. I see you pinned this issue.

**Comment by Iamlooker** [comment]
> BTW, the link "[on GitHub](https://github.com/Droid-ify/Droid-ify/issues/new)" on the [Community](https://droidify.eu.org/community) page is 404. It should be to [here](https://github.com/Droid-ify/client/issues/new) .

I created a PR just now, Thanks for reporting
