### ISSUE TITLE
[BUG] Installation status hangs starting from version 0.5.9 Patch 2

### ISSUE THREAD

**Issue by varaki** [Droid-ify/client#543]
**Describe the bug**
When installing any application from the store by pressing the Install button it starts downloading the app and installs it correctly, but the UI keeps showing the Cancel button. It does not change after installation finishes.

**To Reproduce**
1. Open any app from the store
2. Press the Install button
3. The button changes to "Cancel"
4. The button keeps showing "Cancel" after the installation finishes (as if it would not detect that the app is installed)

**Expected behavior**
After installation the app should detect, that it's finished and the button text should change to "Launch"

**Screenshots**
https://github.com/Droid-ify/client/issues/543#issuecomment-1779767471

**Smartphone (please complete the following information):**
 - Device: Poco X3 Pro
 - OS: Android 13.1 (ArrowOS)
 - Version 0.5.9 Patch 2-3-4

**Additional context**
It was working fine with Version 0.5.9 Patch 1

**Comment by Iamlooker** [comment]
Can you please share a video please. It would help with reproducibility

**Comment by varaki** [comment]
Sure, I'll upload one, when I get to my computer.
Two additional things:
1. It works fine when switching from Root installer to Session installer
2. As far as I remember, when using the update all button in the updates section the problem does not occurr even with the Root installer

**Comment by varaki** [comment]
I updated the issue, after I started going back to find the last working version and it turned out that it was the 0.5.9 Patch 1.
So something might have been introduced in patch 2.

**Comment by varaki** [comment]
> Can you please share a video please. It would help with reproducibility

Here's the screen record of the issue:

https://github.com/Droid-ify/client/assets/23281360/db653b9d-cd49-4966-ac1d-8657da86cdd0

**Comment by Iamlooker** [comment]
I will try testing something in the telegram group as I don't have root access in my device

**Comment by nahuhh** [comment]
Fwiw, related behavior:
using session installer, the install prompt has been repeating. 

1. Tap update on an app on app details screen
2. Press back to go back to droidify main screen
3. Switch apps
4. When download finishes, tap install in the system notification
5. Droidify opens and shows the "install/cancel" dialog
6. Tapping install begins the install
7. It hangs (shows cancel on droidify) and eventually tries to install the apk again (the "install/cancel" dialog reappears).

note: this behavior was definitely not present prior to 0.5.9 branch. I havent reinstalles and retested patch1 etc. But it _was_ working on 0.5.8 and prior

**Comment by Iamlooker** [comment]
@nahuhh Have you tried Patch 5? If it is atill present then please open a new issue I will address the fix in it.

**Comment by nahuhh** [comment]
Yes. Persists
