### ISSUE TITLE
[BUG] Syncing and Fetching slows down the device

### ISSUE THREAD

**Issue by Lijukay** [Droid-ify/client#546]
**Describe the bug**
The device slows down when fetching and syncing the repositories.

**To Reproduce**
1. Open the app
2. Click on the Sync button

**Expected behavior**
The device should not slow down.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Redmi Note 10 Pro]
 - OS: [e.g. Android 13]
 - Version [0.5.9 Patch 4]

**Comment by Iamlooker** [comment]
Fixed in one of the previous commits, and will be available in next release.

You can download the latest alpha builds from our [Telegram Community](https://t.me/droidifyc) or [Actions Tab](https://github.com/Droid-ify/client/actions/workflows/build_debug.yml)
