### ISSUE TITLE
Make app icons more round

### ISSUE THREAD

**Issue by Fxsch** [Droid-ify/client#549]
**Is your feature request related to a problem? Please describe.**
I think the current roundness of the corners of app icons looks a little ugly and doesn't fit into the overall design.
Screenshot for context:
![Screenshot_20231029-215222_Droid-ify](https://github.com/Droid-ify/client/assets/77849217/77a9deca-aed5-4de1-a47e-3be4b208daac)

**Describe the solution you'd like**
Change the roundness of those icons' corners to what it is on the app details page.
Screenshot for context:
![Screenshot_20231029-215248_Droid-ify](https://github.com/Droid-ify/client/assets/77849217/6d5abecf-2ae1-4097-b39f-0ed24d1a781c)

**Comment by Iamlooker** [comment]
I will need to test this first. I think sharp corners add more shape to already round-ish ui of the app, but i will try new stuff

**Comment by Erudition** [comment]
Seems like the point is more that the design is inconsistent, there's more rounding on the app page than in the list

**Comment by Fxsch** [comment]
Why was it changed back? At the end of the day it's not my decision, I'm just wondering
