### ISSUE TITLE
[BUG] double trouble with installs

### ISSUE THREAD

**Issue by hetszunyukapanyanyimonyok** [Droid-ify/client#550]
**Describe the bug**
Installing updates bug.
As usually download all updates at once with the dedicated button and after that I install them manually.
With the lastest update 0.5.9 patch 5
This happens:
When I press install updtae it wants to install the previous installed app  again and than if I press cancel or install offers the program what I originally wanted to install.

**To Reproduce**
1. Go to already downloaded app.
2. Click on install update
3. Offer previous program to install

**Expected behavior**
When pressing the install updtaes button give that app installer not others.

**Screenshots**
Just updated if I can I will upload one.

**Smartphone (please complete the following information):**
 - Device: OnePlus 7p
 - OS: [e.g. Android 11
 - Version [e.g. v0.5.9 patch 5

**Additional context**
Thank you for you work on this app!

**Comment by Iamlooker** [comment]
I will try to look into this, thanks for reporting

**Comment by Hub-O-Gits** [comment]
I'm on a later version of the app, and this happens to me almost every time I use the Update All option.

App ver = 0.6.3
Installer type = Session Installer

Scenario: Let's say 4 apps are due for updating. I press Update All, and after everything has finished downloading, I pull down the notification tray, tap on one of the updates. That navigates to the app's page in Droid-ify, the Install dialog pops up, and I tap Install. After that's finished, but before I can select another app, I get the same Install/Cancel popup for one of the other updates, while I'm still on the page for the app I just installed. And that prompt will recur after each of the other 3 updates, regardless of whether I've already updated it, or press Cancel every time - it doesn't make any difference; it will occur 4 times in all. Also, when the next batch of updates is due, if the previous cursed repeater app happens to be amongst them again, it will often be the repeater app for that session as well.

PS: Please fix the title of this bug report, so it's more search-friendly. "Double trouble" is trying to be cute, and this isn't just double. So perhaps something like: [BUG] Update All causes repeat install prompts

Thank you. Love this app either way.
