### ISSUE TITLE
Option for Swiping between Apps in search (index) page

### ISSUE THREAD

**Issue by inson1** [Droid-ify/client#560]
**Describe the solution you'd like**
I would like to have option in settings for swiping left/right between Apps in search (index) page

**Comment by inson1** [comment]
@Iamlooker sorry, do you know, how do you move through images in your gallery? swiping left/right. 
If I want to read read new x apps descriptions and I find navigation right know annoying. I have go to app, back to index page and click on other app...... Swiping would be easier.
Do you get it now?

**Comment by Iamlooker** [comment]
I get it now, but I think there is already a issue regarding this

**Comment by inson1** [comment]
#171

**Comment by inson1** [comment]
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
