### ISSUE TITLE
[BUG] #543 persists on v0.5.9 Patch 5

### ISSUE THREAD

**Issue by nahuhh** [Droid-ify/client#566]
**Describe the bug**
Repeated install prompts when using `session` installer. 

**To Reproduce**
https://github.com/Droid-ify/client/issues/543#issuecomment-1803117193

**Expected behavior**
Install prompts only once

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: 
 - OS: Android 10
 - Version 

**Additional context**
Related: https://github.com/Droid-ify/client/issues/543
Note: Behavior was not present on versions lower than 0.5.9

**Comment by Iamlooker** [comment]
Fixed, you should test this in Telegram Group Alpha -> [Here](https://t.me/droidifyc)

**Comment by nahuhh** [comment]
I definitely dont use telegram

can upload on github?

**Comment by Iamlooker** [comment]
[app-alpha.zip](https://github.com/Droid-ify/client/files/13625373/app-alpha.zip)

**Comment by nahuhh** [comment]
Crashes immediately

armv8 android 10

**Comment by Iamlooker** [comment]
Weird, can you get crash logs?

**Comment by nahuhh** [comment]
Im not near a pc, perhaps later

immediate crash

**Comment by Iamlooker** [comment]
> Im not near a pc, perhaps later
> 

Sure

**Comment by nahuhh** [comment]
It appears that none of the debug builds work on my device (i tried various github actions builds from before and after 0.5.9)

**Comment by Iamlooker** [comment]
What skin of Android are you using? OneUI, Stock, or some custom ROM?

**Comment by nahuhh** [comment]
EMUI. Stock huawei

**Comment by Iamlooker** [comment]
Can you logs? If possible now.

**Comment by nahuhh** [comment]
closing as it appears to be fixed in 0.6.x
