### ISSUE TITLE
[BUG] [0.5.9 Patch5] Root installer not working properly

### ISSUE THREAD

**Issue by Undisputed00x** [Droid-ify/client#569]
**Describe the bug**
Having selected the root installer, droidify still uses session manager instead of the selected root installer, to clarify when selecting root the pop up window to grant root access is working and as a root installer im using AM manager which is also configured as a default installer.

But when selecting legacy installer Droidify selects my root installer (AM manager).

**To Reproduce**
1. Go to 'a random app'
2. Click on 'install.'
3. See error

**Expected behavior**
When installation finishes the rooted installer should pop up instead of getting installed automatically by session installer

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Poco X3 Pro
 - OS: Android 13
 - Version 0.5.9 Patch 5

**Comment by nahuhh** [comment]
Still on 0.6.1?

**Comment by Undisputed00x** [comment]
@nahuhh yes

**Comment by Iamlooker** [comment]
we only support magisk's libsu, so if you are using any other root solution it might not work

**Comment by Undisputed00x** [comment]
im using KernelSu also AM Manager still works so im gonna close the issue
