### ISSUE TITLE
Retain position while browsing apps

### ISSUE THREAD

**Issue by candroid-man** [Droid-ify/client#571]
If you click on an app, then go back, it will start you from the beginning/top of the list. I want to be able to browse through apps and keep my place so I can continue looking through the apps.

**Comment by Iamlooker** [comment]
Can you share a video of the issue as on my devices it retains location

**Comment by candroid-man** [comment]
Sorry for the wait: https://nextcloud.candroid.cloud/s/747tKbPxpKnNkpr

**Comment by Iamlooker** [comment]
> Sorry for the wait: 

Thats fine, I was and will be offline for few days anyways.

> 
> Also I am using the Pixel 6 Pro on GrapheneOS


This issue seems weird and u reproducible. I will try to write a more robust fix in next release
