### ISSUE TITLE
[BUG] HTTP 3xx redirects cause: "Repository unreachable"

### ISSUE THREAD

**Issue by warren-bank** [Droid-ify/client#572]
test: [repo](https://warren-bank.github.io/fdroid/repo?fingerprint=E991BE73E9C4A5302B844DBF90151D9E599FBA212ACCD1A970802A74C9903078)

notes:
* [v0.5.7](https://github.com/Droid-ify/client/releases/tag/v0.5.7) and older works
* [v0.5.8](https://github.com/Droid-ify/client/releases/tag/v0.5.8) and newer shows error: "Repository unreachable"
* [all commits](https://github.com/Droid-ify/client/compare/v0.5.7...v0.5.8) between these 2 tags

**Comment by Iamlooker** [comment]
Redirects are not supported because it makes the app more vulnerable to phishing attacks and other MitM like attacks.

**Comment by warren-bank** [comment]
Could "follow HTTP redirects?" be added as an expert option under Settings?
* its default value could be: "no"
* but by explicitly enabling it, users would gain the ability to add repos that have this technical requirement

fwiw, it works in both "Foxy Droid" and "Neo Store".
