### ISSUE TITLE
Use shorthand notation for patches

### ISSUE THREAD

**Issue by o0nd7ots** [Droid-ify/client#580]
I do not like the `<version> patch X` scheme of versioning.
It's unnecessarily long and often does not display well.

**Describe the solution you'd like**
Please use a [conventional naming scheme](https://en.wikipedia.org/wiki/Software_versioning#Semantic_versioning) like `0.5.9-2`

Besides Wikipedia I recall Archwiki talking about and encouraging this scheme, but I cannot find it.
(if comebody can link it, please do)

**Describe alternatives you've considered**
I think there are no alternatives if we do not want to change the whole numbering approach

**Additional context**
I get this is a personal preference but I think that I am not alone, and that shortcomings that I pointed out are universally recognized.

**Comment by o0nd7ots** [comment]
For the record:  this notation is used in some places, like here
![image](https://github.com/Droid-ify/client/assets/124466962/ec66dde4-1d33-4e1e-86ba-2e75c23f1983)


@Iamlooker can I please get your opinion on this?

**Comment by Iamlooker** [comment]
I will do this next time. It was to just show the update in a more user friendly way. But fine.

**Comment by o0nd7ots** [comment]
Thanks.

I can see your point with the verbose names, but I think using a typical semantic naming scheme will unify stuff that people see and make it easier in that way.

I have also heard the `0.59-2` naming scheme, but i think what comes after the dash is the build number.
Just throwing it out here.

**Comment by Iamlooker** [comment]
This is fixed in new release.

I will be following x.y.z (X- Major, Y- Minor, Z- Patch) semantics from now-on

**Comment by o0nd7ots** [comment]
Thanks!
