### ISSUE TITLE
[BUG] Swiping images zooms instead of zooming

### ISSUE THREAD

**Issue by s38b35M5** [Droid-ify/client#583]
**Describe the bug**
Some (not all, so perhaps tied to uploaded image type) images on the app summary page, when the screen is touched to swipe, zoom the current image rather than swiping to the next image. I was careful to ensure nothing is interfering with my screen before submission of this issue.

**To Reproduce**
1. Go to https://www.f-droid.org/packages/io.github.muntashirakon.Music/ 
2. Click on any preview image
3. Touch the screen to swipe to the next image
4. See image zoomed rather than swiped

**Expected behavior**
Next image should be displayed instead of zooming.

**Screenshots**

https://github.com/Droid-ify/client/assets/138058715/0a9d0da5-5bdd-4724-97d1-ec30e3abea99

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: LineagOS 19.1
 - Version 0.5.9 patch 5

**Comment by Iamlooker** [comment]
You can download the latest alpha builds from our [Telegram Community](https://t.me/droidifyc) or
Try the even more recent builds in [Actions Tab](https://github.com/Droid-ify/client/actions/workflows/build_debug.yml), these might be more unstable then alpha builds

**Comment by uli-on** [comment]
@Iamlooker Experienced this for the first time today, after upgrading Android to v13, and alpha 4 has fixed this for me. Thanks :)
