### ISSUE TITLE
[BUG] No update notification (0.5.9p5)

### ISSUE THREAD

**Issue by woj-tek** [Droid-ify/client#585]
**Describe the bug**
After updating to v0.5.9 patch 5 there is no notification about updates available

**To Reproduce**
Hmm... just install a couple of apps and wait for them to be updated. There is no notification and they are only listed in "updates" tab when app is opened.

**Expected behavior**
There should be a notification.

I DO have enabled "Notify about updates". I don't have enabled "Automatically update apps".

It work just fine in previous version.

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy A52s 5G
 - OS:  OneUI 5.1 / Android 13
 - Version v0.5.9 patch 5

**Comment by Iamlooker** [comment]
Plean join telegram group and test the alpha build.

**Comment by woj-tek** [comment]
If someone is looking for a link (couldn't find it, only in sources: https://t.me/droidify) but I don't see any alpha build.

Though, would it be possible to make it available here in releases as pre-release?

**Comment by Iamlooker** [comment]
https://t.me/droidifyc

**Comment by Iamlooker** [comment]
Fixed in c711aee9bf63b9a316034b5964d492f7b887f5fe

**Comment by unoukujou** [comment]
> Fixed in [c711aee](https://github.com/Droid-ify/client/commit/c711aee9bf63b9a316034b5964d492f7b887f5fe)

I don't get any notifications no matter what I do.

Android TV, nvidia shield, droidify 0.7.1, android 11

No issues with notifications in any other apps.

Droidify lists the updates available when I open the app and check the updates section, but I never receive any notifications about it. Notifications are enabled for Droidify in the Android system settings. Notifications are enabled in droidify settings as well.
