### ISSUE TITLE
[Feature request] support fdroidrepos:// scheme for adding repositories 

### ISSUE THREAD

**Issue by proletarius101** [Droid-ify/client#62]
The official fdroidclient support fdroidrepos:// and fdroidrepo:// schemes for adding repositories: https://sourcegraph.com/gitlab.com/fdroid/fdroidclient/-/blob/app/src/main/AndroidManifest.xml?L365:31&subtree=true

This makes sure third party repositories can be added to Droid-ify directly from browsers.

**Comment by Bugaddr** [comment]
Duplicate #33
