### ISSUE TITLE
Add Samourai Wallet repo by default

### ISSUE THREAD

**Issue by Pinipon88** [Droid-ify/client#626]
Hi, I just wanted to ask you if you could add the Samourai Wallet repository by default.

https://samouraiwallet.com/download/fdroid

URL
https://repo.samourai.io/fdroid/repo

Fingerprint
5318AFA280284855CF5D0027AA54517769F461D735980B1FB0854CEAE8E072A5

Thanks

**Comment by Iamlooker** [comment]
Added and will be available in next release.
