### ISSUE TITLE
[BUG] 6.0.1 doesn't import favorites

### ISSUE THREAD

**Issue by Turhvjbufv** [Droid-ify/client#629]
**Describe the bug**
Droidify doesn't import favorites 
**To Reproduce**
Export settings, reinstall droidify and import settings back, favorites is still empty
**Expected behavior**
Should insert favorites
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: A72
 - OS: 13
 - Version 0.6.1

**Additional context**
Works in 0.5.9 v5

**Comment by Iamlooker** [comment]
Will fix in next release

**Comment by Iamlooker** [comment]
Fixed with d3e0f2a6eed0181fdf0035e421a842f7426b0af6
