### ISSUE TITLE
[BUG] "Sync repositories automatically" not working

### ISSUE THREAD

**Issue by casperklein** [Droid-ify/client#650]
**Describe the bug**

The "sync repositories automatically" function does not work for me at all (I've tried all available settings). Currently it's set to "always". But I've never received an update notification ("notificy for updates" is enabled).

When I open the app from time to time, there are no updates listed. When I then manually sync the repositories, the updates are listed and can be installed.

I couldn't find a log or something to check, if automatic syncs are ever triggert.

**Expected behavior**
The repositories should be synced from time to time.

**Smartphone (please complete the following information):**
 - Device: Samsung S23
 - OS: Android 14
 - Version 0.6.1 (I started using this app with version 0.5.9, since then, automatic sync did never work).

**Additional context**
I gave the app all permissions that are possible + disabled any power saving options for this app.

**Comment by BabyOilJohnson** [comment]
I also have the same issue here.

**Comment by Beerman0815** [comment]
Unfortunally, I have the same issue. 
I have to start the sync manually, after that I get all the updates.

P7P with GOS

**Comment by chloyster** [comment]
I've been having the same issue for an extremely long time now. I was hopeful one of the recent updates that mentioned it would fix it but I'm still having the problem unfortunately.

**Comment by mo-st** [comment]
Same issue in P8 GOS Android 14. Included logs in case that might help. 

[Droid-ify-log.txt](https://github.com/Droid-ify/client/files/14628495/Droid-ify-log.txt)

**Comment by kabe-inc** [comment]
This issue is marked as completed, but I am still having the same problem with 0.63.

Samsung S21 on Android 14.

**Comment by Iamlooker** [comment]
Can you switch the "Auto Sync" setting twice. I mean change it to something and revert back to your desired setting. Also check if the "Ignore Battery Optimization" is checked.

**Comment by kabe-inc** [comment]
Disabling Auto-Sync gives me the red Require Background Access warning even though battery optimization is disabled in app settings, so I'm not sure what else needs to be done. 

![Screenshot_20240416_000051_Droid-ify](https://github.com/Droid-ify/client/assets/72587902/c9c6c14b-d804-48bc-b295-1f27d0e1c6a0)

![Screenshot_20240416_000059_Settings](https://github.com/Droid-ify/client/assets/72587902/275e822c-080c-435d-962d-1ea65a5effff)
