### ISSUE TITLE
[BUG] Default repo name has changed to 'My First F-Droid Repo Demo'

### ISSUE THREAD

**Issue by secretServant** [Droid-ify/client#653]
**Describe the bug**
The default F-Droid repo is named 'My First F-Droid Repo Demo', the same is true for F-Droid archive, 'My First F-Droid Archive Demo'

**Expected behavior**
Demo implies pre-release. I think it should look like the original F-Droid app, just simply 'F-Droid' or 'F-Droid Archive'. I'm not sure what changed but Droid-ify used to display it in a more concise manner.

**Additional context**
Perhaps adding a editable name field when adding repos would be appropriate.  Even deleting and re-adding the default repo results in the weird Demo naming convention.

**Comment by TheLastProject** [comment]
Not a Droid-ify bug, the f-droid.org people messed up and literally set "My First F-Droid Repo Demo" as repo name: https://web.archive.org/web/20240127232559/https://f-droid.org/repo/

**Comment by mondlicht-und-sterne** [comment]
In the F-Droid Client, the F-Droid Client Basic and the F-Droid Classic 

it has not changed the "F-Droid Main Repo" name.

**Comment by GameOverFlowChart** [comment]
> Actually went into the Repo menu fully expecting being able to manually change the name. Apparently I was wrong. For some repos, regardless of potential mess up, editing the name would absolutely be a great feature to have.

I see that as a new way for bugs. There should be a single source of truth. If the repos can broadcast names, that name should be used. If the name makes no sense, talk to the devs of that repo and let them change it. If something fishy happens with a repo you will miss it because you renamed it locally.
