### ISSUE TITLE
[BUG] share button supplies non functional link

### ISSUE THREAD

**Issue by rudolfmu** [Droid-ify/client#654]
In previous versions when viewing an app and then clicking the share button a link to the app on the Fdroid website was provided. Now a link to the droidify website is provided like this:
https://droidify.eu.org/app/?id=com.looker.droidify&repo_address=https://f-droid.org/repo
which leads to a "page not found".
Please revert to the link to Fdroid.org. I used it a lot when posting app recommendations.

**Comment by Iamlooker** [comment]
This link is sharable to another droidify user, But this should also be fixed for fdroid repository for now

The issue was caused because they renamed the repository to "My First Demo Repo". But should be fixed for now :)
