### ISSUE TITLE
[Crash] Low memory

### ISSUE THREAD

**Issue by opk12** [Droid-ify/client#667]
**Describe the bug**
My phone has little free internal memory. I tap to download 4-5 big apps and put down the phone for a while. Then I tap the notification to install. But Droid-ify crashes.

Possibly Android is auto-deleting the cached packages to free up space? https://developer.android.com/training/data-storage/app-specific#internal-remove-cache

```
FATAL EXCEPTION: DefaultDispatcher-worker-3
Process: com.looker.droidify, PID: 26856
java.io.FileNotFoundException: /data/user/0/com.looker.droidify/cache/releases/[snip long hex name].apk (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at com.looker.installer.installers.session.SessionInstaller.install(SourceFile:64)
	at com.looker.installer.InstallManager$installer$1.invokeSuspend(SourceFile:230)
    [snip]
```

**Smartphone (please complete the following information):**
Droid-ify 0.6.1 on Android 7.1

**Comment by vertigo220** [comment]
It crashed on me even just starting the install, i.e. before it even started downloading. On two separate apps. And then it crashed when I hit install after they were downloaded. Yet, despite this, they still installed, making the crashing even more bizarre, as despite being low on space, there was still enough for them to install.
