### ISSUE TITLE
reproducible builds

### ISSUE THREAD

**Issue by IzzySoft** [Droid-ify/client#674]
@obfusk just informed me that Droid-ify is "sooo close" to being reproducible – were it not for some nondeterministically ordered locales (she [pointed here](https://github.com/Droid-ify/client/blob/acf2953122ee154d5400232a5f48e3321720d768/core/common/build.gradle.kts#L55) for that).

Nondeterministic here means: their order varies. So simply adding a sort to that code behind the above link should make the app RB.

Would you go for that? @obfusk can certainly help if you have technical questions (which I can hardly answer, not being an Android dev). Thanks in advance!

**Comment by Iamlooker** [comment]
@obfusk The code referenced by Izzy seems to be [this](https://github.com/Droid-ify/client/blob/acf2953122ee154d5400232a5f48e3321720d768/core/common/build.gradle.kts#L55)

This code is for fetching the locales to show them inside the settings page. I am unable to understand how this relates to reproducible builds? I haven't looked into this much so any help is appreciated 😃

**Comment by obfusk** [comment]
> I am unable to understand how this relates to reproducible builds

Reproducible Builds means different people building from the same source get the exact same APK. But if the order of the locales varies (e.g. `de` before or after `es`), the APK is different.

<details>

```diff
--- x/classes.dex.dump	2024-02-12 00:40:18.512137218 +0100
+++ y/classes.dex.dump	2024-02-12 00:40:20.228144819 +0100
@@ -2,8 +2,8 @@
 Opened 'classes.dex', DEX version '035'
 DEX file header:
 magic               : 'dex\n035\0'
-checksum            : 3a2370ab
-signature           : 855c...7cc0
+checksum            : 3c3b7138
+signature           : 9408...12c3
 file_size           : 4725916
 header_size         : 112
 link_size           : 0
@@ -271622,8 +271622,8 @@
       outs          : 49
       insns size    : 105 16-bit code units
 | com.looker.core.common.BuildConfig.<clinit>:()V
-|: const-string v0, "de"
-|: const-string v1, "hi"
+|: const-string v0, "hi"
+|: const-string v1, "de"
 |: const-string v2, "pt"
 |: const-string v3, "lt"
 |: const-string v4, "lv"
@@ -271640,8 +271640,8 @@
 |: const-string v15, "eo"
 |: const-string v16, "nb-rNO"
 |: const-string v17, "it"
-|: const-string v18, "es"
-|: const-string v19, "iw"
+|: const-string v18, "iw"
+|: const-string v19, "es"
 |: const-string v20, "ar"
 |: const-string v21, "vi"
 |: const-string v22, "ja"
@@ -271651,8 +271651,8 @@
 |: const-string v26, "nl"
 |: const-string v27, "nn"
 |: const-string v28, "zh-rCN"
-|: const-string v29, "fi"
-|: const-string v30, "be"
+|: const-string v29, "be"
+|: const-string v30, "fi"
 |: const-string v31, "ru"
 |: const-string v32, "bg"
 |: const-string v33, "fr"
@@ -271660,9 +271660,9 @@
 |: const-string v35, "sl"
 |: const-string v36, "ca"
 |: const-string v37, "sr"
-|: const-string v38, "kn"
-|: const-string v39, "sv"
-|: const-string v40, "or"
+|: const-string v38, "or"
+|: const-string v39, "kn"
+|: const-string v40, "sv"
 |: const-string v41, "ko"
 |: const-string v42, "gl"
 |: const-string v43, "pt-rBR"
```

**Comment by obfusk** [comment]
Per the docs:

> The order of the files in a FileTree is not stable, even on a single computer.

So sorting the list should make it identical in every build, regardless of that.

**Comment by obfusk** [comment]
Though even if the `FileTree` order was stable, you're storing the locales in a `HashSet`, which "makes no guarantees as to the iteration order of the set". So that's the real issue here.

**Comment by IzzySoft** [comment]
Now, that was fast :star_struck: Thanks!

**Comment by obfusk** [comment]
> I'll let you know if the next release is indeed reproducible when it's out :)

v0.6.2 is indeed reproducible :)
