### ISSUE TITLE
Start of Droid-ify from my application

### ISSUE THREAD

**Issue by henrichg** [Droid-ify/client#679]
Please, how to start Droid-if from my application?

I want to open in Droid-ify application PhoneProfilesPlus (PPP), but when are not repositories refreshed, displayed is old latest version of PPP.

How my applicaiton starts Droid-ify:

```
Intent intent = new Intent(Intent.ACTION_VIEW,
    Uri.parse("market://details?id=sk.henrichg.phoneprofilesplus"));

intent.setPackage("com.looker.droidify");

activity.startActivity(intent);
```

Thanks.

**Comment by Iamlooker** [comment]
You can simple do:
```
Intent intent = new Intent(Intent.ACTION_VIEW,
    Uri.parse("https://apt.izzysoft.de/fdroid/index/apk/sk.henrichg.phoneprofilesplus"));

activity.startActivity(intent);
```

Or:
```
Intent intent = new Intent(Intent.ACTION_VIEW,
    Uri.parse("https://droidify.eu.org/app/?id=sk.henrichg.phoneprofilesplus"));

activity.startActivity(intent);
```

The second one is a sure shot way to open the app in Droid-ify but I dont think it will work with other clients

**Comment by henrichg** [comment]
I want to open Droid-ify application, not IzzyOnDroid web page with PPP.

**Comment by Iamlooker** [comment]
IzzyDroid has officially allowed Droid-ify to open their URL on Droid-ify, so this URL should open in Droid-ify with most certainty

**Comment by henrichg** [comment]
Intent intent = new Intent(Intent.ACTION_VIEW,
    Uri.parse("https://apt.izzysoft.de/fdroid/index/apk/sk.henrichg.phoneprofilesplus"));
This opens web page, even when is isnstalled Droid-ify. Not for me.

Intent intent = new Intent(Intent.ACTION_VIEW,
    Uri.parse("https://droidify.eu.org/app/?id=sk.henrichg.phoneprofilesplus"));
This opens Droid-ify, but currently is not possible to test, if it is latest (refreshed) version of PPP app view. :-(

**Comment by Iamlooker** [comment]
Sorry but yes, there is no way to test if the app is outdated

Doing this is not planned for now and for any near future too. Sorry

**Comment by henrichg** [comment]
Not good. :-( 
Thanks for help.
