### ISSUE TITLE
[BUG] FAB in Updates tab covers part of the view

### ISSUE THREAD

**Issue by quazar-omega** [Droid-ify/client#684]
**Describe the bug**
In the Updates tab, when the list of apps to update is full enough to reach the bottom of the screen, the floating action button "Update all" covers part of the last entry it without the ability to be scrolled out of the view.

**To Reproduce**
1. Go to 'Updates' tab
2. Have a list of apps to be updated that covers the entire height of the screen
3. Scroll down to the bottom
4. The FAB can't be moved out of the way to allow seeing the last entry completely

**Expected behavior**
There should be a spacer that makes the view longer so that the button could be scrolled out of view.

**Screenshots**
<img alt="Screenshot_20240318-190100_Droid-ify" height="500px" src="https://github.com/Droid-ify/client/assets/56311398/597ec579-5dc6-4f65-b85e-335c9b87d4fe">

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A5 2017
 - OS: Android 8.0.0 / Samsung Experience 9.0
 - Version v0.6.1

**Additional information**
Related to #361

**Comment by quazar-omega** [comment]
I've just tried the latest updated (0.6.2) but I'm actually still experiencing the issue

**Comment by Iamlooker** [comment]
Very weird, i will try something new

**Comment by quazar-omega** [comment]
Could it be related to the screen resolution?

**Comment by Iamlooker** [comment]
No I think its an Android version issue

**Comment by quazar-omega** [comment]
Oh, I see! Let me know if you need me to run any test apk
