### ISSUE TITLE
App crash quickly after launch[Crash]

### ISSUE THREAD

**Issue by alr86** [Droid-ify/client#686]
**Describe the bug**
Sometimes when I open droid-ify,  it crash quickly

**To Reproduce**
I don't know

**Smartphone:**
 - Device: Redmi note 9 with CrDroid v10.0
 - OS: Android 14
 - Version 0.6.1

**Additional context**
Crash log in "App bot responed" popup:
https://paste.crdroid.net/McnPgG

**Comment by Iamlooker** [comment]
seems like some sort of database corruption, sorry but I think you need to clear the data

**Comment by alr86** [comment]
The problem is still exist after clear the data

**Comment by alr86** [comment]
When I disabled all Magisk modules, the problem was solved, since the problem does not occur at the moment, I cannot say exactly which module is the problem, but I will close this issue anyway.
