### ISSUE TITLE
[BUG] Ignore Battery Optimization

### ISSUE THREAD

**Issue by derei** [Droid-ify/client#693]
Update 0.6.2 brings a rather annoying feature: ignore battery optimization.
Why is it annoying? Because every time the app is opened, it spams the user with a popup dialogue, and the feature can't be disabled in settings.

Why should I allow the app to run in the background? I don't want that. I want it to run when I decide. Please allow that check and popup to be disabled in settings.

**Comment by islam2hamy** [comment]
+1

**Comment by derei** [comment]
> Yep, I totally agree. Since it doesn't have a (separate) notification channel, it can't be turned off. I don't think it's intentional, though.

I'm sure is not intentional, but it should be addressed. Hopefully the dev sees this report and decides to do something about it. Fingers crossed!

**Comment by Iamlooker** [comment]
Next update will fix this.

**Comment by yonoff** [comment]
Please fix ASAP

**Comment by andrzej-gmt** [comment]
App shouldn't ask for background permission if automatic upgrades and notification of updates are disabled in settings.
Even if app needs background permission, it would be nice to not nag the user, who prefer to optimize battery use.

**Comment by matteobtt** [comment]
I agree, this app doesn't need to be always on, it only needs to wake up every now and then to check for updates, so asking users to turn off battery optimization for this use case is absolutely wrong! If the app never wakes up in the background, it is a symptom that the API to handle background tasks is not being used properly.

See [Optimize for Doze and App Standby](https://developer.android.com/training/monitoring-device-state/doze-standby) and [Background work overview](https://developer.android.com/develop/background-work/background-tasks).

**Comment by NearestWater262** [comment]
please fix, it keeps asking me endlessly >:(

**Comment by Iamlooker** [comment]
Releasing an update in few minutes
