### ISSUE TITLE
[BUG] SessionInstaller's EXTRA_INSTALLER_PACKAGE_NAME shouldn't be "com.android.vending"

### ISSUE THREAD

**Issue by BLumia** [Droid-ify/client#696]
**Describe the bug**

https://github.com/Droid-ify/client/blob/14cb9e03dfc67da9dd4f11eca1c7b9a8175f786c/installer/src/main/java/com/looker/installer/installers/session/SessionInstallerService.kt#L30

Currently, if SessionInstaller was used, the installer package name will be `com.android.vending`, which indicate the package is installed by Google Play instead of Droid-ify.

**To Reproduce**

Reproducing steps will be more complicated. You will need to find an app which can show its install source (via `getInstallerPackageName` API)

**Expected behavior**

Droid-ify's package name should be used

**Screenshots**

N/A

**Smartphone (please complete the following information):**
 - Not related

**Additional context**
Let me know if you need any additional information.

**Comment by BLumia** [comment]
Tested in 0.6.3 and seems work as intended (`getInstallerPackageName()` will get `com.looker.droidify`).

**Comment by Iamlooker** [comment]
On some specific vendors, they don't support other package names. And others automatically determine the package name. Its just some select vendors who use these API's correctly. So for general audience this is fine
