### ISSUE TITLE
[BUG] Selecting a specific version to be installed does not function properly

### ISSUE THREAD

**Issue by Uneccessary** [Droid-ify/client#706]
**Describe the bug**
When you try to select a version, for example to download an App from IzzyOnDroid instead of F-Droid it will still and always download the version which is recommended on top, no matter which Repo you choosed to download it from.

**To Reproduce**
1. Go to a app which offers multiply versions or repo's to download from
2. Click on a version which is not recommended
3. It will still download the recommended version, not the one you choosed

**Expected behavior**
The selected version get's downloaded and installed

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A33 5G
 - OS: Android 14
 - Version 0.6.3

**Comment by spider1163** [comment]
I cannot reproduce the error, can you give an app as example?

**Comment by Uneccessary** [comment]
I will provide a video and the app version

**Comment by Uneccessary** [comment]
I will open a new issue.
