### ISSUE TITLE
Sometimes droid-ify remains blocked for several minutes during sync

### ISSUE THREAD

**Issue by serrq** [Droid-ify/client#724]
OnePlus CPH2399
Android 14
Droid-ify 0.6.3 (fdroid)

![1000109716](https://github.com/Droid-ify/client/assets/113377431/4aaf9497-b645-41f2-b681-e0151ce1e686)

**Comment by Iamlooker** [comment]
Getting logs will help a lot, I have not been able to find the reason behind this issue

**Comment by Iamlooker** [comment]
Sorry but I cannot help without logs
