### ISSUE TITLE
[BUG] Really laggy after update

### ISSUE THREAD

**Issue by Jojoba24** [Droid-ify/client#733]
**Describe the bug**
Since I updated to 1.30 the Launcher is really slow and unusable.

**To Reproduce**
1. Update to 1.30
2. Lag

**Expected behavior**
No lag. It was fine before.

**Smartphone (please complete the following information):**
 - Device: S9+
 - OS: Android 10 and One UI 2.5

**Additional context**
Already cleared the cache and restarted the Phone.

**Comment by Iamlooker** [comment]
Which launcher?
