### ISSUE TITLE
Tabs?

### ISSUE THREAD

**Issue by okgamr** [Droid-ify/client#743]
**Is your feature request related to a problem? Please describe.**
I may want to use Droid-ify easier with some tabs at the bottom, just like F-droid

**Describe the solution you'd like**
Just the addition of the tabs makes me happy

**Describe alternatives you've considered**
I didn't try anything else than F-droid and Droid-ify, maybe this is the only client for F-droid materialised. If there are more, I'll be happy to use them as well

**Additional context**
Nah, just that

**Comment by meenbeese** [comment]
Duplicate of #10
