### ISSUE TITLE
Fennec f-droid update

### ISSUE THREAD

**Issue by sankhababu** [Droid-ify/client#756]
Sir 

Actually this is not bug report, I didn't find any other category for my quarry, please excuse me 🙏

Fennec f-droid and Mull (f-droid release) not updating for a long time. They are still in 125, whereas Mull (direct from Divest os through FFupdater), Iceraven, Waterfox already updated to 127.

Sir, do you have any information that F-droid stopped Fennec etc., after moving of the repos to Mozilla from Github?
Or any other problems like corruption in releted f-droid links (this happened before as I read in old Raddit post). ?

If you please....

Regards 
🙏

**Comment by SkewedZeppelin** [comment]
They are updated now, there was an issue on F-Droid.org compile server now fixed: https://forum.f-droid.org/t/how-to-keep-mull-browser-updated/26523/3

**Comment by sankhababu** [comment]
> They are updated now, there was an issue on F-Droid.org compile server now fixed: https://forum.f-droid.org/t/how-to-keep-mull-browser-updated/26523/3

Thank you for the information.
Is there any other way to get early Fennec other than f-droid, as we get Mull?

**Comment by SkewedZeppelin** [comment]
Fennec F-Droid is only available via the F-Droid.org repo

**Comment by sankhababu** [comment]
Thanks
