### ISSUE TITLE
[BUG] The "Require Background Access" banner still appears, even when permission is granted, upon changing any setting within the app.

### ISSUE THREAD

**Issue by Uneccessary** [Droid-ify/client#757]
**Describe the bug**
The "Require Background Access" banner appears even when the app is set to always run in the background, when changing any setting regardless of whether the settings are related or not. It disappears when the settings menu is reopened.

**To Reproduce**
1. Go to Settings
2. Change any setting
3. The banner will appear

**Expected behavior**

**Screenshots**
The banner only appears if the permission is not given and an relevant setting is beeing changed.

**Smartphone (please complete the following information):**
 - OS: Android 14
 - Version 0.6.3

**Additional context**
See attachments

**Comment by Uneccessary** [comment]
https://github.com/Droid-ify/client/assets/145043411/8a1772da-06aa-48bf-a310-687babab778e

**Comment by Iamlooker** [comment]
Fixed

**Comment by neo-neo1** [comment]
Encountered this same problem on a new install. Current newest version on Android 14
