### ISSUE TITLE
Add Futo repo to optional repositories

### ISSUE THREAD

**Issue by Handrail9** [Droid-ify/client#768]
**Is your feature request related to a problem? Please describe.**
I use FUTO Voice & GrayJay and find them to be great applications with an F-Droid repo
**Describe the solution you'd like**
I would like the FUTO F-Droid repo to be added https://app.futo.org/fdroid/repo/
**Describe alternatives you've considered**
Adding it manually (Difficult to do on devices like Android TV)
**Additional context**

**Comment by shuvashish76** [comment]
None of the FUTO apps are opensource. Let's not promote "source available" only projects to Droidify users. Yes Droidify has added multiple repository by default at the same time I think add new repository option is there for reasons. IMO Droidify shouldn't add all the repositories available in the wild especially repos that host proprietary/source available apps.

**Comment by Wave6677** [comment]
I see no reason why source available is an inherently bad thing, not to mention [there is a repo hosting a modified Google play store.](https://nanolx.org/fdroid/repo/?fingerprint=862ED9F13A3981432BF86FE93D14596B381D75BE83A1D616E2D44A12654AD015) While being "modified" to work with MicroG, it is still a proprietary app.
FUTO apps are useful tools that do not spy on the end user. This can be checked in source. If you do not want the repo, you can simply not enable. I never said it should be enabled by default, and any user enabling repos should know _what's in the repo_ before they enable it. That should not be Droid-ify's responsibility.

**Comment by freshgum-bubbles** [comment]
As an interested bystander, and someone who regularly makes use of F-Droid / Droid-ify, I'm quite interested in the initial response to this issue :-)

@shuvashish76 Firstly, are you a maintainer of Droid-ify, a representative of the project, or just a member of the community?  This isn't immediately clear, so it seems wise to ask to defuse any potential confusion later on.

> None of the FUTO apps are opensource. Let's not promote "source available" only projects to Droidify users.

Could I ask why?  Is there official documentation discouraging the addition of source-available apps, or past precedent which dictates how requests for new repositories should be handled?  I'm not familiar with maintainer politics / policies here, so perhaps you could shed some light on that for us if possible? :-)

> IMO Droidify shouldn't add all the repositories available in the wild especially not the repos that host proprietary/source available apps.

...why not?  At first glance, having an immediately-available list of repositories sounds like quite a good idea; it'd make discovery a lot easier, and would encourage the federation of apps across repositories (and, buzzwords / fanaticism aside, federation in software is generally quite a good thing).  I'd understand if the project wished not to take risks by promoting potentially-dangerous software, however (though that feature could, of course, be paired with an appropriate disclaimer regarding liability and risk.)

The obvious follow-up question is, *if* not, what would be used as a deciding factor when considering new repositories? (This links back into the question above.)

**Comment by BabyOilJohnson** [comment]
This has been added in the latest release, so I think we should close this issue.
