### ISSUE TITLE
randomly sort apps

### ISSUE THREAD

**Issue by 4rtemis-4rrow** [Droid-ify/client#799]
**Is your feature request related to a problem? Please describe.**
at some points, you just want to discover some apps, see what's out there, google play solves this by showing you what's currently popular, and since that's impossible without tracking

**Describe the solution you'd like**
a random sort feature, preferably allowing you to specify a set date where the app must have been updated (eg. show all apps that were updated after 1/1/2024, and shuffle them)

**Describe alternatives you've considered**
a discovery page might also work, though I think the first suggestion is better

**Comment by shuvashish76** [comment]
IMO "what's new" sort is good enough for discovering new apps without adding more complexity to the app.

> eg. show all apps that were updated after 1/1/2024, and shuffle them

One of the main reason people love Droidify is it's simple to use. I think this king of features increase complexity of the app unnecessarily.
You like it or not F-Droid will never have any algorithm to discover apps similar to PlayStore for obvious reasons.

**Comment by Iamlooker** [comment]
Well put together@shuvashish76, also about "exploribility" I might think about this in future but honestly, not on my list right now. Sorry
