### ISSUE TITLE
[BUG] Your subdomain https://www.droidify.eu.org you linked to over at F-Droid is smimming belly up

### ISSUE THREAD

**Issue by s3nnet** [Droid-ify/client#830]
**Describe the bug**
While your  domain droidify.eu.org is fine,  your subdomain https://www.droidify.eu.org you linked to over at F-Droid is smimming belly up.

**To Reproduce**
self-explanatory

**Expected behavior**
Make the web link you left over at F-Droid work or replace it with your working domain

**Screenshots**
Screenshot attached

**Smartphone (please complete the following information):**
irrelevant (same both for desktop and mobile)

**Additional context**
Courtesy of s3nnet.de
![Doidify_www_error](https://github.com/user-attachments/assets/9604e694-95a6-4a0c-853e-585ae0302a55)

**Comment by grote** [comment]
what has this to do with CalyxOS? sounds like a droidify issue

**Comment by DJCrashdummy** [comment]
interestingly although https://www.droidify.eu.org/ seems completely offline (not even shows a 404 site), https://droidify.eu.org/ is up and running. *(just the banner stating the latest version is quite outdated.)*

**Comment by Iamlooker** [comment]
I never provided a website, maybe someone else did.

**Comment by licaon-kter** [comment]
Done in https://gitlab.com/fdroid/fdroiddata/-/commit/4e6af098a340f56f353e93b12f8cc188602814fb

**Comment by Iamlooker** [comment]
Thanks a lot
