### ISSUE TITLE
[BUG] "0B / -1B" in repository synchronisation notification.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [Droid-ify/client#833]
**Describe the bug**

When I synchronise the repositories, the notification displays "0B / -1B" as its progress.

**To Reproduce**

1.	Install https://f-droid.org/repo/com.looker.droidify_630.apk
1.	Synchronise the repositories.

**Expected behavior**

I should actually be informed of the progress.

**Screenshots**

> ![Screenshot_20240907-182953](https://github.com/user-attachments/assets/ec6bfb1f-ad7c-4161-bd50-9a4518e5e0b9)

**Smartphone (please complete the following information):**

 - Device: `cpe:/h:fairphone:fairphone_5`
 - OS: https://fairphone-android-builds.ams3.digitaloceanspaces.com/FP5/A14/FP5-UT27-factory.zip
 - Version: FP5.UT27.B.059.20240809

**Additional context**

**Comment by Iamlooker** [comment]
Fixed and will be available innext release
