### ISSUE TITLE
Open App Details from Settings

### ISSUE THREAD

**Issue by jonas-w** [Droid-ify/client#853]
**Is your feature request related to a problem? Please describe.**

When an app is installed with Droid-Ify, it is displayed in the system settings as "App installed from Droid-Ify." When you install apps from stores like the Play Store or the GrapheneOS App Store, you can click there and access the app information. Unfortunately, this is not possible with Droid-Ify.

**Describe the solution you'd like**

Implement the SHOW_APP_INFO intent.

The only changes that are needed are the following lines:
In the AndroidManifest.xml
```xml
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTask"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.SHOW_APP_INFO" />
            </intent-filter>
... already existing intent filters etc.
```

In ScreenActivity.kt
```kotlin
 open fun handleIntent(intent: Intent?) {
        when (intent?.action) {
            // Current code handling ACTION_VIEW ...

            Intent.ACTION_SHOW_APP_INFO -> {
                val packageName = intent.getStringExtra(Intent.EXTRA_PACKAGE_NAME)
                if (packageName != null) {
                    val fragment = currentFragment
                    if (fragment !is AppDetailFragment) {
                        navigateProduct(packageName)
                    }
                }


            }
        }
    }
```
> [!IMPORTANT]  
> This requires API Level 24 (current min API Level is 23)

**Describe alternatives you've considered**

Maybe it's possible to conditionally only enable the Intent-Filter for this on API Level >= 24, this wouldn't need a min API level bump.

**Additional context**

I've tested these changes on my Phone, and it works without a problem.
I copied bits from the deeplink VIEW Intent.

**Comment by Bnyro** [comment]
You can probably use `tools:targetApi="n"` on the intent filter to suppress the warning, there's no need to bump the min SDK version.

Older Android versions just won't see / be able to call use that intent filter.

**Comment by Iamlooker** [comment]
Can you create a PR for this, if possible. I won't be able to work on this anytime soon
